import { authorized, clean, json, number, unauthorized } from "../admin-shared.js";

async function getComposition(env,produtoId){const r=await env.DB.prepare(`SELECT pm.material_id,pm.quantidade AS quantidade_unitaria,m.nome,m.unidade,m.estoque,m.custo_medio,COALESCE(m.perda_percentual,0) AS perda_percentual FROM produto_materiais pm JOIN materiais m ON m.id=pm.material_id WHERE pm.produto_id=? AND m.ativo=1 ORDER BY m.nome COLLATE NOCASE`).bind(produtoId).all();return r.results||[]}
async function getReserved(env,materialId){const r=await env.DB.prepare(`SELECT COALESCE(SUM(quantidade),0) AS reservado FROM ordem_material_reservas WHERE material_id=?`).bind(materialId).first();return number(r?.reservado)}
async function syncPrinter(env,...ids){for(const impId of [...new Set(ids.filter(Boolean))]){const rodando=await env.DB.prepare(`SELECT id FROM ordens_impressao WHERE impressora_id=? AND status='imprimindo' LIMIT 1`).bind(impId).first();await env.DB.prepare(`UPDATE impressoras_3d SET status=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND status NOT IN ('manutencao','offline')`).bind(rodando?'imprimindo':'livre',impId).run()}}

async function list(env){
  const [ordens,impressoras]=await Promise.all([
    env.DB.prepare(`SELECT o.*,p.nome AS produto_nome,m.nome AS modelo_nome,m.versao,m.arquivo_nome,m.principal,m.cor_recomendada,m.preview_r2_key,i.nome AS impressora_nome,(SELECT COUNT(*) FROM ordem_material_reservas r WHERE r.ordem_id=o.id) AS materiais_reservados FROM ordens_impressao o JOIN produtos p ON p.id=o.produto_id LEFT JOIN modelos_3d m ON m.id=o.modelo_3d_id LEFT JOIN impressoras_3d i ON i.id=o.impressora_id ORDER BY CASE o.status WHEN 'imprimindo' THEN 0 WHEN 'fila' THEN 1 WHEN 'pausada' THEN 2 ELSE 3 END,o.id DESC LIMIT 200`).all(),
    env.DB.prepare(`SELECT * FROM impressoras_3d WHERE ativo=1 ORDER BY nome COLLATE NOCASE`).all()
  ]);
  return json({sucesso:true,ordens:ordens.results||[],impressoras:impressoras.results||[]});
}

export async function onRequestGet({request,env}){if(!(await authorized(request,env)))return unauthorized(env);return list(env)}

export async function onRequestPost({request,env}){
  if(!(await authorized(request,env)))return unauthorized(env);
  const b=await request.json().catch(()=>({}));const produtoId=Number(b.produto_id),impressoraId=Number(b.impressora_id)||null,quantidade=Math.max(1,Math.trunc(number(b.quantidade,1)));let modeloId=Number(b.modelo_3d_id)||null;
  if(!produtoId)return json({sucesso:false,mensagem:'Selecione o produto.'},400);
  const produto=await env.DB.prepare(`SELECT id,nome FROM produtos WHERE id=? AND ativo=1`).bind(produtoId).first();if(!produto)return json({sucesso:false,mensagem:'Produto não encontrado.'},404);
  if(!modeloId){const principal=await env.DB.prepare(`SELECT id FROM modelos_3d WHERE produto_id=? AND ativo=1 AND principal=1 ORDER BY id DESC LIMIT 1`).bind(produtoId).first();modeloId=principal?.id||null}
  let modelo=null;if(modeloId){modelo=await env.DB.prepare(`SELECT id,peso_g,tempo_minutos,r2_key FROM modelos_3d WHERE id=? AND produto_id=? AND ativo=1`).bind(modeloId,produtoId).first();if(!modelo)return json({sucesso:false,mensagem:'Modelo 3D inválido para este produto.'},400)}
  if(impressoraId){const imp=await env.DB.prepare(`SELECT id FROM impressoras_3d WHERE id=? AND ativo=1`).bind(impressoraId).first();if(!imp)return json({sucesso:false,mensagem:'Impressora não encontrada.'},404)}
  const composicao=await getComposition(env,produtoId);if(!composicao.length)return json({sucesso:false,mensagem:'Configure a composição do produto antes de criar uma ordem.'},400);
  const reservas=[];for(const item of composicao){const necessidade=number(item.quantidade_unitaria)*quantidade*(1+number(item.perda_percentual)/100);const reservado=await getReserved(env,item.material_id);const disponivel=Math.max(0,number(item.estoque)-reservado);if(disponivel+1e-9<necessidade)return json({sucesso:false,mensagem:`Estoque disponível insuficiente de ${item.nome}. Necessário: ${necessidade.toFixed(2)} ${item.unidade}; disponível após reservas: ${disponivel.toFixed(2)} ${item.unidade}.`},409);reservas.push({...item,necessidade})}
  const peso=number(modelo?.peso_g)*quantidade,tempo=Math.trunc(number(modelo?.tempo_minutos)*quantidade);const r=await env.DB.prepare(`INSERT INTO ordens_impressao (produto_id,modelo_3d_id,impressora_id,quantidade,status,peso_previsto_g,tempo_previsto_min,observacoes) VALUES (?,?,?,?,?,?,?,?)`).bind(produtoId,modeloId,impressoraId,quantidade,'fila',peso,tempo,clean(b.observacoes,800)||null).run();const ordemId=r.meta?.last_row_id;if(!ordemId)return json({sucesso:false,mensagem:'Não foi possível criar a ordem.'},500);
  try{await env.DB.batch(reservas.map(x=>env.DB.prepare(`INSERT INTO ordem_material_reservas (ordem_id,material_id,quantidade) VALUES (?,?,?)`).bind(ordemId,x.material_id,x.necessidade)));return json({sucesso:true,id:ordemId,modelo_3d_id:modeloId,materiais_reservados:reservas.length,mensagem:'Ordem criada e materiais reservados.'},201)}catch(error){await env.DB.prepare(`DELETE FROM ordens_impressao WHERE id=?`).bind(ordemId).run().catch(()=>{});return json({sucesso:false,mensagem:'Não foi possível reservar os materiais da ordem.'},500)}
}

async function conclude(env,ordem,impressoraId){
  const reservas=(await env.DB.prepare(`SELECT r.material_id,r.quantidade,m.nome,m.unidade,m.estoque,m.custo_medio FROM ordem_material_reservas r JOIN materiais m ON m.id=r.material_id WHERE r.ordem_id=?`).bind(ordem.id).all()).results||[];if(!reservas.length)return json({sucesso:false,mensagem:'Esta ordem não possui materiais reservados.'},409);
  for(const x of reservas)if(number(x.estoque)+1e-9<number(x.quantidade))return json({sucesso:false,mensagem:`O estoque de ${x.nome} ficou menor que a reserva. Ajuste o estoque antes de concluir.`},409);
  const cfg=await env.DB.prepare(`SELECT custo_extra FROM produto_precificacao WHERE produto_id=?`).bind(ordem.produto_id).first();const custoMateriais=reservas.reduce((s,x)=>s+number(x.quantidade)*number(x.custo_medio),0);const custoExtraTotal=number(cfg?.custo_extra)*number(ordem.quantidade);const custoTotal=custoMateriais+custoExtraTotal;const custoUnitario=custoTotal/number(ordem.quantidade);
  const pr=await env.DB.prepare(`INSERT INTO producoes (produto_id,quantidade,custo_unitario,custo_total,observacoes) VALUES (?,?,?,?,?)`).bind(ordem.produto_id,ordem.quantidade,custoUnitario,custoTotal,`Gerada pela ordem de impressão #${ordem.id}`).run();const producaoId=pr.meta?.last_row_id;if(!producaoId)return json({sucesso:false,mensagem:'Não foi possível registrar a produção.'},500);
  const stm=[];for(const x of reservas){const anterior=number(x.estoque),novo=anterior-number(x.quantidade);stm.push(env.DB.prepare(`UPDATE materiais SET estoque=estoque-?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND estoque>=?`).bind(x.quantidade,x.material_id,x.quantidade),env.DB.prepare(`INSERT INTO estoque_movimentos (material_id,tipo,quantidade,saldo_anterior,saldo_novo,valor_unitario,origem,referencia,observacoes) VALUES (?,?,?,?,?,?,?,?,?)`).bind(x.material_id,'saida',x.quantidade,anterior,novo,number(x.custo_medio),'ordem-impressao',String(ordem.id),`Conclusão da ordem #${ordem.id}`),env.DB.prepare(`INSERT INTO producao_itens (producao_id,material_id,quantidade_unitaria,quantidade_consumida,custo_unitario) VALUES (?,?,?,?,?)`).bind(producaoId,x.material_id,number(x.quantidade)/number(ordem.quantidade),x.quantidade,number(x.custo_medio)))}
  stm.push(env.DB.prepare(`UPDATE produtos SET estoque=estoque+?,custo=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?`).bind(ordem.quantidade,custoUnitario,ordem.produto_id),env.DB.prepare(`DELETE FROM ordem_material_reservas WHERE ordem_id=?`).bind(ordem.id),env.DB.prepare(`UPDATE ordens_impressao SET status='concluida',impressora_id=?,concluido_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=?`).bind(impressoraId,ordem.id));
  try{const results=await env.DB.batch(stm);const materialUpdates=results.filter((_,i)=>i<reservas.length*3&&i%3===0);if(materialUpdates.some(r=>!r.meta?.changes))throw new Error('O estoque mudou durante a conclusão.');await syncPrinter(env,ordem.impressora_id,impressoraId);return json({sucesso:true,producao_id:producaoId,custo_unitario:custoUnitario,custo_total:custoTotal,mensagem:'Ordem concluída, materiais consumidos e produto acabado adicionado ao estoque.'})}catch(error){await env.DB.prepare(`DELETE FROM producoes WHERE id=?`).bind(producaoId).run().catch(()=>{});return json({sucesso:false,mensagem:error.message||'Não foi possível concluir a ordem.'},500)}
}

export async function onRequestPut({request,env}){
  if(!(await authorized(request,env)))return unauthorized(env);const b=await request.json().catch(()=>({})),id=Number(b.id),status=clean(b.status,20),impressoraId=Number(b.impressora_id)||null;if(!id||!['fila','imprimindo','pausada','concluida','cancelada','falhou'].includes(status))return json({sucesso:false,mensagem:'Ordem ou status inválido.'},400);
  const atual=await env.DB.prepare(`SELECT * FROM ordens_impressao WHERE id=?`).bind(id).first();if(!atual)return json({sucesso:false,mensagem:'Ordem não encontrada.'},404);if(['concluida','cancelada','falhou'].includes(atual.status))return json({sucesso:false,mensagem:'Esta ordem já foi encerrada.'},409);
  if(impressoraId){const ocupada=await env.DB.prepare(`SELECT id FROM ordens_impressao WHERE impressora_id=? AND status='imprimindo' AND id<>?`).bind(impressoraId,id).first();if(ocupada&&status==='imprimindo')return json({sucesso:false,mensagem:'Essa impressora já está imprimindo outra ordem.'},409)}
  if(status==='concluida')return conclude(env,atual,impressoraId||atual.impressora_id||null);
  if(['cancelada','falhou'].includes(status)){await env.DB.batch([env.DB.prepare(`UPDATE ordens_impressao SET status=?,impressora_id=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?`).bind(status,impressoraId,id),env.DB.prepare(`DELETE FROM ordem_material_reservas WHERE ordem_id=?`).bind(id)]);await syncPrinter(env,atual.impressora_id,impressoraId);return json({sucesso:true,mensagem:'Ordem encerrada e materiais liberados.'})}
  const iniciado=status==='imprimindo'?'COALESCE(iniciado_em,CURRENT_TIMESTAMP)':'iniciado_em';await env.DB.prepare(`UPDATE ordens_impressao SET status=?,impressora_id=?,iniciado_em=${iniciado},atualizado_em=CURRENT_TIMESTAMP WHERE id=?`).bind(status,impressoraId,id).run();await syncPrinter(env,atual.impressora_id,impressoraId);return json({sucesso:true,mensagem:'Ordem atualizada; materiais permanecem reservados.'});
}

export async function onRequest(c){if(c.request.method==='GET')return onRequestGet(c);if(c.request.method==='POST')return onRequestPost(c);if(c.request.method==='PUT')return onRequestPut(c);return json({sucesso:false,mensagem:'Método não permitido.'},405)}
