import { authorized, clean, json, unauthorized } from "../admin-shared.js";

const validStatus=new Set(['lead','contato','negociacao','cliente','inativo']);
const validTipo=new Set(['petshop','clinica','distribuidor','outro']);
function parse(body){return{tipo:validTipo.has(clean(body.tipo,30))?clean(body.tipo,30):'petshop',nome:clean(body.nome,160),cidade:clean(body.cidade,100)||null,estado:clean(body.estado,40)||null,contato_nome:clean(body.contato_nome,120)||null,whatsapp:clean(body.whatsapp,60)||null,instagram:clean(body.instagram,120)||null,email:clean(body.email,160)||null,status:validStatus.has(clean(body.status,30))?clean(body.status,30):'lead',ultima_interacao:clean(body.ultima_interacao,30)||null,proximo_retorno:clean(body.proximo_retorno,30)||null,interesse:clean(body.interesse,300)||null,observacoes:clean(body.observacoes,1200)||null}}

export async function onRequestGet({request,env}){if(!(await authorized(request,env)))return unauthorized(env);const q=clean(new URL(request.url).searchParams.get('q'),100),like=`%${q}%`;const r=await env.DB.prepare(`SELECT * FROM crm_contatos WHERE ativo=1 AND (?='' OR nome LIKE ? OR COALESCE(cidade,'') LIKE ? OR COALESCE(contato_nome,'') LIKE ? OR COALESCE(whatsapp,'') LIKE ?) ORDER BY CASE status WHEN 'negociacao' THEN 0 WHEN 'contato' THEN 1 WHEN 'lead' THEN 2 WHEN 'cliente' THEN 3 ELSE 4 END,COALESCE(proximo_retorno,'9999-12-31'),nome COLLATE NOCASE LIMIT 500`).bind(q,like,like,like,like).all();return json({sucesso:true,contatos:r.results||[]})}
export async function onRequestPost({request,env}){if(!(await authorized(request,env)))return unauthorized(env);const d=parse(await request.json().catch(()=>({})));if(!d.nome)return json({sucesso:false,mensagem:'Informe o nome do estabelecimento.'},400);const r=await env.DB.prepare(`INSERT INTO crm_contatos (tipo,nome,cidade,estado,contato_nome,whatsapp,instagram,email,status,ultima_interacao,proximo_retorno,interesse,observacoes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(d.tipo,d.nome,d.cidade,d.estado,d.contato_nome,d.whatsapp,d.instagram,d.email,d.status,d.ultima_interacao,d.proximo_retorno,d.interesse,d.observacoes).run();return json({sucesso:true,id:r.meta?.last_row_id,mensagem:'Contato cadastrado.'},201)}
export async function onRequestPut({request,env}){if(!(await authorized(request,env)))return unauthorized(env);const b=await request.json().catch(()=>({})),id=Number(b.id),d=parse(b);if(!id||!d.nome)return json({sucesso:false,mensagem:'Contato inválido.'},400);const r=await env.DB.prepare(`UPDATE crm_contatos SET tipo=?,nome=?,cidade=?,estado=?,contato_nome=?,whatsapp=?,instagram=?,email=?,status=?,ultima_interacao=?,proximo_retorno=?,interesse=?,observacoes=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND ativo=1`).bind(d.tipo,d.nome,d.cidade,d.estado,d.contato_nome,d.whatsapp,d.instagram,d.email,d.status,d.ultima_interacao,d.proximo_retorno,d.interesse,d.observacoes,id).run();if(!r.meta?.changes)return json({sucesso:false,mensagem:'Contato não encontrado.'},404);return json({sucesso:true,mensagem:'Contato atualizado.'})}
export async function onRequestDelete({request,env}){if(!(await authorized(request,env)))return unauthorized(env);const id=Number(new URL(request.url).searchParams.get('id'));if(!id)return json({sucesso:false,mensagem:'Contato inválido.'},400);await env.DB.prepare(`UPDATE crm_contatos SET ativo=0,status='inativo',atualizado_em=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();return json({sucesso:true,mensagem:'Contato arquivado.'})}
export async function onRequest(c){if(c.request.method==='GET')return onRequestGet(c);if(c.request.method==='POST')return onRequestPost(c);if(c.request.method==='PUT')return onRequestPut(c);if(c.request.method==='DELETE')return onRequestDelete(c);return json({sucesso:false,mensagem:'Método não permitido.'},405)}