CREATE TABLE IF NOT EXISTS pet_fotos (id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,url TEXT NOT NULL,public_id TEXT,ordem INTEGER NOT NULL DEFAULT 1,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_pet_fotos_tag ON pet_fotos(tag_codigo,ordem,id);
