import { adminAutorizado } from "../_lib/admin-auth.js";

const HEADERS={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:HEADERS});
const clean=(value,max=120)=>String(value??"").trim().slice(0,max);
async function authorized(request,env){return adminAutorizado(request,env)}
async function setup(env){const columns=await env.DB.prepare("PRAGMA table_info(tags)").all(),names=new Set((columns.results||[]).map(item=>item.name));for(const[name,type]of[["modelo","TEXT DEFAULT 'nfc'"],["lote","TEXT"],["preparo_status","TEXT DEFAULT 'estoque'"],["gravada_em","TEXT"],["testada_em","TEXT"],["vendida_em","TEXT"]])if(!names.has(name))await env.DB.prepare(`ALTER TABLE tags ADD COLUMN ${name} ${type}`).run()}
function randomCode(){const year=String(new Date().getFullYear()).slice(-2),bytes=crypto.getRandomValues(new Uint8Array(4)),number=((bytes[0]<<24)|(bytes[1]<<16)|(bytes[2]<<8)|bytes[3])>>>0;return`BIRX-${year}-${String(number%1000000).padStart(6,"0")}`}
function unauthorized(env){return json({sucesso:false,autenticado:false,mensagem:env.TAG_ADMIN_TOKEN?"Sessão administrativa inválida ou expirada.":"Configure TAG_ADMIN_TOKEN na Cloudflare."},401)}
export async function onRequestGet({request,env}){if(!await authorized(request,env))return unauthorized(env);try{await setup(env);const url=new URL(request.url),search=clean(url.searchParams.get("busca"),100),like=`%${search}%`;
const [result,resumo]=await Promise.all([
  env.DB.prepare(`SELECT codigo,ativada,bloqueada,data_criacao AS dataCriacao,data_ativacao AS dataAtivacao,modelo,lote,COALESCE(preparo_status,'estoque') AS preparoStatus,gravada_em AS gravadaEm,testada_em AS testadaEm,vendida_em AS vendidaEm FROM tags WHERE ?='' OR codigo LIKE ? OR COALESCE(lote,'') LIKE ? ORDER BY id DESC LIMIT 200`).bind(search,like,like).all(),
  env.DB.prepare(`SELECT COUNT(*) AS total,
    SUM(CASE WHEN COALESCE(ativada,0)=0 AND COALESCE(preparo_status,'estoque')='estoque' THEN 1 ELSE 0 END) AS estoque,
    SUM(CASE WHEN COALESCE(ativada,0)=0 AND COALESCE(preparo_status,'estoque')='gravada' THEN 1 ELSE 0 END) AS gravadas,
    SUM(CASE WHEN COALESCE(ativada,0)=0 AND COALESCE(preparo_status,'estoque')='testada' THEN 1 ELSE 0 END) AS testadas,
    SUM(CASE WHEN COALESCE(ativada,0)=0 AND COALESCE(preparo_status,'estoque')='vendida' THEN 1 ELSE 0 END) AS vendidas,
    SUM(CASE WHEN COALESCE(ativada,0)=1 THEN 1 ELSE 0 END) AS ativadas
    FROM tags`).first()
]);return json({sucesso:true,tags:(result.results||[]).map(tag=>({...tag,status:Number(tag.ativada)===1?"ativada":tag.preparoStatus||"estoque"})),resumo:{total:Number(resumo?.total||0),estoque:Number(resumo?.estoque||0),gravadas:Number(resumo?.gravadas||0),testadas:Number(resumo?.testadas||0),vendidas:Number(resumo?.vendidas||0),ativadas:Number(resumo?.ativadas||0)}})}catch(error){console.error("admin-tags GET",error);return json({sucesso:false,mensagem:"Não foi possível listar as tags."},500)}}
export async function onRequestPost({request,env}){if(!await authorized(request,env))return unauthorized(env);try{await setup(env);const body=await request.json().catch(()=>({})),action=clean(body.acao,30);
if(action==="criar"){const quantity=Math.min(100,Math.max(1,Number.parseInt(body.quantidade,10)||1)),model=clean(body.modelo,40),batch=clean(body.lote,60);if(!["essential","nfc","nfc-identificacao"].includes(model))return json({sucesso:false,mensagem:"Modelo inválido."},400);const created=[];for(let attempt=0;created.length<quantity&&attempt<quantity*10;attempt++){const code=randomCode();try{await env.DB.prepare(`INSERT INTO tags(codigo,ativada,bloqueada,modelo,lote,preparo_status) VALUES(?,0,0,?,NULLIF(?,''),'estoque')`).bind(code,model,batch).run();created.push(code)}catch(error){if(!String(error.message).toLowerCase().includes("unique"))throw error}}if(created.length!==quantity)return json({sucesso:false,mensagem:"Não foi possível gerar todos os códigos."},500);return json({sucesso:true,mensagem:`${created.length} tag${created.length===1?"":"s"} cadastrada${created.length===1?"":"s"}.`,codigos:created},201)}
if(action==="status"){const code=clean(body.codigo,40).toUpperCase(),status=clean(body.status,20);if(!code||!["estoque","gravada","testada","vendida"].includes(status))return json({sucesso:false,mensagem:"Dados inválidos."},400);const current=await env.DB.prepare("SELECT ativada FROM tags WHERE codigo=? LIMIT 1").bind(code).first();if(!current)return json({sucesso:false,mensagem:"Tag não encontrada."},404);if(Number(current.ativada)===1)return json({sucesso:false,mensagem:"Uma tag ativada não pode ter o preparo alterado."},409);const field=status==="gravada"?",gravada_em=CURRENT_TIMESTAMP":status==="testada"?",testada_em=CURRENT_TIMESTAMP":status==="vendida"?",vendida_em=CURRENT_TIMESTAMP":"";await env.DB.prepare(`UPDATE tags SET preparo_status=?${field} WHERE codigo=?`).bind(status,code).run();return json({sucesso:true,mensagem:`Tag marcada como ${status}.`})}
if(action==="remover"){const code=clean(body.codigo,40).toUpperCase();if(!code)return json({sucesso:false,mensagem:"Código inválido."},400);const current=await env.DB.prepare("SELECT codigo,ativada,COALESCE(preparo_status,'estoque') AS status FROM tags WHERE codigo=? LIMIT 1").bind(code).first();if(!current)return json({sucesso:false,mensagem:"Tag não encontrada."},404);if(Number(current.ativada)===1||current.status!=="estoque")return json({sucesso:false,mensagem:"Somente tags ainda em estoque podem ser removidas."},409);const result=await env.DB.prepare("DELETE FROM tags WHERE codigo=? AND ativada=0 AND COALESCE(preparo_status,'estoque')='estoque' AND NOT EXISTS (SELECT 1 FROM pets WHERE pets.tag_codigo=tags.codigo)").bind(code).run();const changes=Number(result.meta?.changes||0);if(changes!==1)return json({sucesso:false,mensagem:"A tag possui vínculo ou não pode ser removida."},409);return json({sucesso:true,mensagem:`Tag ${code} removida.`})}
if(action==="remover-estoque"){const search=clean(body.busca,100);if(!search)return json({sucesso:false,mensagem:"Digite o lote ou código na busca antes de remover em massa."},400);const like=`%${search}%`;const result=await env.DB.prepare("DELETE FROM tags WHERE ativada=0 AND COALESCE(preparo_status,'estoque')='estoque' AND (codigo LIKE ? OR COALESCE(lote,'') LIKE ?) AND NOT EXISTS (SELECT 1 FROM pets WHERE pets.tag_codigo=tags.codigo)").bind(like,like).run();const changes=Number(result.meta?.changes||0);return json({sucesso:true,mensagem:`${changes} tag${changes===1?"":"s"} em estoque removida${changes===1?"":"s"}.`,removidas:changes})}
return json({sucesso:false,mensagem:"Ação inválida."},400)}catch(error){console.error("admin-tags POST",error);return json({sucesso:false,mensagem:"Não foi possível atualizar as tags."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
