const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=1000)=>String(value??"").trim().slice(0,max);
function cookies(request){const result={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();if(!key)continue;try{result[key]=decodeURIComponent(part.slice(at+1).trim())}catch{result[key]=part.slice(at+1).trim()}}return result}
function token(request){const jar=cookies(request);for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT id,email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
async function owns(env,tag,email){return env.DB.prepare("SELECT id,nome FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,email).first()}
async function setup(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_agendamentos(id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,tipo TEXT NOT NULL,titulo TEXT NOT NULL,data_hora TEXT NOT NULL,clinica TEXT,veterinario TEXT,endereco TEXT,observacoes TEXT,status TEXT NOT NULL DEFAULT 'agendado',criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
function validDate(value){const text=clean(value,30);return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(text)&&Number.isFinite(Date.parse(text))?text.slice(0,16):null}
async function auth(request,env){const current=await session(request,env);return current||json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou. Entre novamente."},401)}
async function reminders(env,email,tag,rows){const now=Date.now(),limit=now+48*60*60*1000;for(const item of rows){const when=Date.parse(item.dataHora);if(item.status!=="agendado"||when<now||when>limit)continue;const window=`agendamento-${item.id}`;await env.DB.prepare(`INSERT OR IGNORE INTO notificacoes_tutor(email,tag_codigo,tipo,janela,titulo,descricao,url) VALUES(?,?,?,?,?,?,?)`).bind(email,tag,"agendamento",window,`Compromisso próximo: ${item.titulo}`,`${item.tipo} em ${new Date(when).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}`,`/tutor.html?agendamento=${item.id}`).run()}}
export async function onRequestGet({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100);if(!tag)return json({sucesso:false,mensagem:"Código da tag não informado."},400);if(!await owns(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);await setup(env);const result=await env.DB.prepare(`SELECT id,tag_codigo AS tagCodigo,tipo,titulo,data_hora AS dataHora,clinica,veterinario,endereco,observacoes,status,criado_em AS criadoEm FROM pet_agendamentos WHERE UPPER(tag_codigo)=UPPER(?) ORDER BY CASE status WHEN 'agendado' THEN 0 ELSE 1 END,datetime(data_hora) ASC,id DESC`).bind(tag).all(),items=result.results||[];await reminders(env,current.email,tag,items);return json({sucesso:true,agendamentos:items})}catch(error){console.error("Erro em agendamentos GET:",error);return json({sucesso:false,mensagem:"Não foi possível carregar os agendamentos."},500)}}
export async function onRequestPost({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10)||null,tag=clean(body.tagCodigo,100),type=clean(body.tipo,20),title=clean(body.titulo,120),date=validDate(body.dataHora),clinic=clean(body.clinica,160),vet=clean(body.veterinario,120),address=clean(body.endereco,240),notes=clean(body.observacoes,1000),status=["agendado","concluido","cancelado"].includes(body.status)?body.status:"agendado";if(!tag||!["consulta","retorno","exame","vacina","outro"].includes(type)||!title||!date)return json({sucesso:false,mensagem:"Informe tipo, título, data e horário."},400);if(!await owns(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);await setup(env);if(id){const found=await env.DB.prepare("SELECT id FROM pet_agendamentos WHERE id=? AND UPPER(tag_codigo)=UPPER(?)").bind(id,tag).first();if(!found)return json({sucesso:false,mensagem:"Agendamento não encontrado."},404);await env.DB.prepare(`UPDATE pet_agendamentos SET tipo=?,titulo=?,data_hora=?,clinica=?,veterinario=?,endereco=?,observacoes=?,status=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND UPPER(tag_codigo)=UPPER(?)`).bind(type,title,date,clinic,vet,address,notes,status,id,tag).run();return json({sucesso:true,mensagem:"Agendamento atualizado com sucesso.",id})}const batch=await env.DB.batch([env.DB.prepare(`INSERT INTO pet_agendamentos(tag_codigo,tipo,titulo,data_hora,clinica,veterinario,endereco,observacoes,status) VALUES(?,?,?,?,?,?,?,?,?)`).bind(tag,type,title,date,clinic,vet,address,notes,status),env.DB.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,?,?,?,?,1,?)`).bind(tag,type==="vacina"?"vacina":"consulta",`Agendado: ${title}`,[clinic,address].filter(Boolean).join(" • ")||null,date,current.email)]);return json({sucesso:true,mensagem:"Agendamento criado e adicionado à timeline.",id:batch[0]?.meta?.last_row_id||null},201)}catch(error){console.error("Erro em agendamentos POST:",error);return json({sucesso:false,mensagem:"Não foi possível salvar o agendamento."},500)}}
export async function onRequestDelete({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag||!await owns(env,tag,current.email))return json({sucesso:false,mensagem:"Agendamento não encontrado."},404);await setup(env);await env.DB.prepare("DELETE FROM pet_agendamentos WHERE id=? AND UPPER(tag_codigo)=UPPER(?)").bind(id,tag).run();return json({sucesso:true,mensagem:"Agendamento excluído."})}catch(error){return json({sucesso:false,mensagem:"Não foi possível excluir o agendamento."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
