import { obterSessaoTutor, petPertenceAoTutor } from "../_lib/auth.js";

const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
async function setup(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_alimentacao(id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,marca TEXT NOT NULL,linha TEXT,tipo TEXT NOT NULL DEFAULT 'seca',quantidade_diaria_g REAL NOT NULL,horarios TEXT NOT NULL,pacote_g REAL NOT NULL,iniciado_em TEXT NOT NULL,alerta_dias INTEGER NOT NULL DEFAULT 5,observacoes TEXT,ativo INTEGER NOT NULL DEFAULT 1,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_alimentacao_historico(id INTEGER PRIMARY KEY AUTOINCREMENT,alimentacao_id INTEGER,tag_codigo TEXT NOT NULL,acao TEXT NOT NULL,resumo TEXT NOT NULL,registrado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`)])}
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00Z`));
const times=value=>[...new Set(clean(value,100).split(",").map(x=>x.trim()).filter(x=>/^([01]\d|2[0-3]):[0-5]\d$/.test(x)))].sort();
function estimate(row){const days=Math.max(1,Math.ceil(Number(row.pacote_g)/Number(row.quantidade_diaria_g))),end=new Date(`${row.iniciado_em}T12:00:00Z`);end.setUTCDate(end.getUTCDate()+days-1);const refill=new Date(end);refill.setUTCDate(refill.getUTCDate()-Number(row.alerta_dias||0));return{duracaoDias:days,terminaEm:end.toISOString().slice(0,10),reporEm:refill.toISOString().slice(0,10)}}
async function notify(env,email,tag,row){const dates=estimate(row),today=new Date().toISOString().slice(0,10);if(dates.reporEm<=today)await env.DB.prepare(`INSERT OR IGNORE INTO notificacoes_tutor(email,tag_codigo,tipo,janela,titulo,descricao,url) VALUES(?,?,'alimentacao',?,?,?,?)`).bind(email,tag,`alimentacao:${row.id}:${dates.reporEm}`,"Hora de repor a alimentação",`O pacote de ${row.marca} está perto do fim. Confira o consumo registrado.`,`/tutor?alimentacao=${encodeURIComponent(tag)}`).run();return dates}
export async function onRequestGet({request,env}){try{const current=await obterSessaoTutor(request,env);if(!current)return json({sucesso:false,autenticado:false},401);await setup(env);const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100);if(!tag||!await petPertenceAoTutor(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const currentFood=await env.DB.prepare(`SELECT id,marca,linha,tipo,quantidade_diaria_g AS quantidadeDiariaG,horarios,pacote_g AS pacoteG,iniciado_em AS iniciadoEm,alerta_dias AS alertaDias,observacoes,ativo FROM pet_alimentacao WHERE UPPER(tag_codigo)=UPPER(?) AND ativo=1 ORDER BY id DESC LIMIT 1`).bind(tag).first();const history=await env.DB.prepare(`SELECT id,acao,resumo,registrado_em AS registradoEm FROM pet_alimentacao_historico WHERE UPPER(tag_codigo)=UPPER(?) ORDER BY id DESC LIMIT 30`).bind(tag).all();let alimentacao=null;if(currentFood){alimentacao={...currentFood,...await notify(env,current.email,tag,{...currentFood,pacote_g:currentFood.pacoteG,quantidade_diaria_g:currentFood.quantidadeDiariaG,iniciado_em:currentFood.iniciadoEm,alerta_dias:currentFood.alertaDias})}}return json({sucesso:true,alimentacao,historico:history.results||[]})}catch(error){console.error("alimentacao GET",error);return json({sucesso:false,mensagem:"Não foi possível carregar a alimentação."},500)}}
export async function onRequestPost({request,env}){try{const current=await obterSessaoTutor(request,env);if(!current)return json({sucesso:false,autenticado:false},401);await setup(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100),marca=clean(body.marca,120),linha=clean(body.linha,120),tipo=["seca","umida","natural","mista","outra"].includes(body.tipo)?body.tipo:"outra",daily=Number(body.quantidadeDiariaG),pack=Number(body.pacoteG),hours=times(Array.isArray(body.horarios)?body.horarios.join(","):body.horarios).join(","),start=clean(body.iniciadoEm,10),alert=Math.min(30,Math.max(0,Number.parseInt(body.alertaDias,10)||0)),notes=clean(body.observacoes,500);if(!tag||!marca||daily<=0||daily>10000||pack<=0||pack>100000||!hours||!validDate(start))return json({sucesso:false,mensagem:"Informe marca, quantidades, horários e data válidos."},400);const pet=await petPertenceAoTutor(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);await env.DB.prepare(`UPDATE pet_alimentacao SET ativo=0,atualizado_em=CURRENT_TIMESTAMP WHERE UPPER(tag_codigo)=UPPER(?) AND ativo=1 AND EXISTS(SELECT 1 FROM pets p WHERE UPPER(p.tag_codigo)=UPPER(pet_alimentacao.tag_codigo) AND LOWER(p.email)=LOWER(?))`).bind(tag,current.email).run();const result=await env.DB.prepare(`INSERT INTO pet_alimentacao(tag_codigo,marca,linha,tipo,quantidade_diaria_g,horarios,pacote_g,iniciado_em,alerta_dias,observacoes) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(tag,marca,linha||null,tipo,daily,hours,pack,start,alert,notes||null).run();const id=result.meta?.last_row_id||null,resumo=`${marca}${linha?` ${linha}`:""} · ${daily} g/dia · pacote de ${pack} g`;await env.DB.prepare("INSERT INTO pet_alimentacao_historico(alimentacao_id,tag_codigo,acao,resumo) VALUES(?,?,'alteracao',?)").bind(id,tag,resumo).run();const dates=estimate({pacote_g:pack,quantidade_diaria_g:daily,iniciado_em:start,alerta_dias:alert});return json({sucesso:true,mensagem:`Alimentação de ${pet.nome||'pet'} atualizada.`,id,...dates},201)}catch(error){console.error("alimentacao POST",error);return json({sucesso:false,mensagem:"Não foi possível salvar a alimentação."},500)}}
export async function onRequestDelete({request,env}){try{const current=await obterSessaoTutor(request,env);if(!current)return json({sucesso:false,autenticado:false},401);await setup(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100);if(!tag||!await petPertenceAoTutor(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado."},404);const result=await env.DB.prepare(`UPDATE pet_alimentacao SET ativo=0,atualizado_em=CURRENT_TIMESTAMP WHERE UPPER(tag_codigo)=UPPER(?) AND ativo=1 AND EXISTS(SELECT 1 FROM pets p WHERE UPPER(p.tag_codigo)=UPPER(pet_alimentacao.tag_codigo) AND LOWER(p.email)=LOWER(?))`).bind(tag,current.email).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Nenhum plano ativo encontrado."},404);await env.DB.prepare("INSERT INTO pet_alimentacao_historico(tag_codigo,acao,resumo) VALUES(?,'encerramento','Plano de alimentação encerrado')").bind(tag).run();return json({sucesso:true,mensagem:"Plano de alimentação encerrado."})}catch(error){console.error("alimentacao DELETE",error);return json({sucesso:false,mensagem:"Não foi possível encerrar."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
