function respostaJson(dados,status=200,cookie=null){const headers=new Headers({'Content-Type':'application/json; charset=UTF-8','Cache-Control':'no-store'});if(cookie)headers.append('Set-Cookie',cookie);return new Response(JSON.stringify(dados),{status,headers})}
async function gerarHash(texto){const dados=new TextEncoder().encode(texto),hash=await crypto.subtle.digest('SHA-256',dados);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function gerarTokenSeguro(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return Array.from(bytes).map(b=>b.toString(16).padStart(2,'0')).join('')}
const texto=(v,max=200)=>String(v??'').trim().slice(0,max);const textoOuNulo=(v,max=500)=>texto(v,max)||null;const somenteNumeros=v=>String(v||'').replace(/\D/g,'');const normalizarEmail=v=>texto(v,254).toLowerCase();const emailValido=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
function validarFotoUrl(valor){const url=texto(valor,1000);if(!url)return null;try{const e=new URL(url);return e.protocol==='https:'&&e.hostname.endsWith('cloudinary.com')?e.toString():null}catch{return null}}
export async function onRequestPost(context){try{const db=context.env.DB,dados=await context.request.json().catch(()=>({}));const codigoNormalizado=texto(dados.codigoTag,40).toUpperCase(),nomePet=texto(dados.nomePet,120),especiePet=texto(dados.especiePet,60),nomeTutor=texto(dados.nomeTutor,120),emailNormalizado=normalizarEmail(dados.email),whatsappNormalizado=somenteNumeros(dados.whatsapp),cepNormalizado=somenteNumeros(dados.cep),cidade=texto(dados.cidade,120),estado=texto(dados.estado,2).toUpperCase(),numero=texto(dados.numero,30);
if(!codigoNormalizado||!nomePet||!especiePet||!nomeTutor||!whatsappNormalizado||!emailNormalizado||!cepNormalizado||!cidade||!estado||!numero)return respostaJson({sucesso:false,mensagem:'Preencha todos os campos obrigatórios.'},400);
if(!emailValido(emailNormalizado))return respostaJson({sucesso:false,mensagem:'Informe um e-mail válido.'},400);if(whatsappNormalizado.length!==11)return respostaJson({sucesso:false,mensagem:'Informe um WhatsApp válido com DDD e 11 números.'},400);if(cepNormalizado.length!==8)return respostaJson({sucesso:false,mensagem:'Informe um CEP válido com 8 números.'},400);if(!/^[A-Z]{2}$/.test(estado))return respostaJson({sucesso:false,mensagem:'Informe um estado válido.'},400);
const tag=await db.prepare(`SELECT codigo,ativada,bloqueada,COALESCE(preparo_status,'estoque') AS preparo_status FROM tags WHERE codigo=? LIMIT 1`).bind(codigoNormalizado).first();if(!tag)return respostaJson({sucesso:false,mensagem:'Tag não encontrada.'},404);if(Number(tag.ativada)===1)return respostaJson({sucesso:false,mensagem:'Esta tag já foi ativada.'},409);if(Number(tag.bloqueada)===1)return respostaJson({sucesso:false,mensagem:'Esta tag está bloqueada.'},403);
const reserva=await db.prepare(`UPDATE tags SET ativada=1,data_ativacao=CURRENT_TIMESTAMP WHERE codigo=? AND ativada=0 AND COALESCE(bloqueada,0)=0`).bind(codigoNormalizado).run();if(Number(reserva.meta?.changes||0)!==1)return respostaJson({sucesso:false,mensagem:'Esta tag já foi ativada ou não está disponível.'},409);
try{await db.prepare(`INSERT INTO pets(tag_codigo,nome,especie,raca,sexo,idade,comportamento,nome_tutor,whatsapp,email,cep,logradouro,bairro,cidade,estado,numero,complemento,foto_url,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(codigoNormalizado,nomePet,especiePet,textoOuNulo(dados.racaPet,120),textoOuNulo(dados.sexoPet,30),textoOuNulo(dados.idadePet,50),textoOuNulo(dados.comportamentoPet,800),nomeTutor,whatsappNormalizado,emailNormalizado,cepNormalizado,textoOuNulo(dados.logradouro,180),textoOuNulo(dados.bairro,120),cidade,estado,numero,textoOuNulo(dados.complemento,180),validarFotoUrl(dados.fotoUrl),'seguro').run()}catch(error){await db.prepare(`UPDATE tags SET ativada=0,data_ativacao=NULL WHERE codigo=? AND NOT EXISTS(SELECT 1 FROM pets WHERE tag_codigo=?)`).bind(codigoNormalizado,codigoNormalizado).run();throw error}
await registrarEventoTimelineSeguro(db,codigoNormalizado,'cadastro','Pet cadastrado',`O perfil de ${nomePet} foi criado e a tag foi ativada.`,emailNormalizado);
const agora=new Date(),token=gerarTokenSeguro(),tokenHash=await gerarHash(token),sessaoExpiraEm=new Date(agora.getTime()+30*24*60*60*1000),ip=context.request.headers.get('CF-Connecting-IP')||context.request.headers.get('X-Forwarded-For')||null,userAgent=context.request.headers.get('User-Agent')||null;
await db.batch([db.prepare(`DELETE FROM sessoes_tutor WHERE email=? AND expira_em<=?`).bind(emailNormalizado,agora.toISOString()),db.prepare(`INSERT INTO sessoes_tutor(email,token_hash,criado_em,expira_em,ultimo_acesso,ip,user_agent,provedor) VALUES(?,?,?,?,?,?,?,'email')`).bind(emailNormalizado,tokenHash,agora.toISOString(),sessaoExpiraEm.toISOString(),agora.toISOString(),ip,userAgent)]);
const cookie=[`orbitek_sessao=${token}`,'Path=/','HttpOnly','SameSite=Lax',`Max-Age=${30*24*60*60}`];if(new URL(context.request.url).protocol==='https:')cookie.push('Secure');return respostaJson({sucesso:true,mensagem:'Tag ativada com sucesso.',redirecionarPara:'/tutor.html'},201,cookie.join('; '))}catch(erro){console.error('Erro ao ativar tag:',erro);return respostaJson({sucesso:false,mensagem:'Não foi possível ativar a tag. Tente novamente.'},500)}}
export function onRequestGet(){return respostaJson({sucesso:false,mensagem:'Método não permitido.'},405)}
async function registrarEventoTimelineSeguro(db,tagCodigo,tipo,titulo,descricao,criadoPor){try{await db.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,?,?,?,CURRENT_TIMESTAMP,1,?)`).bind(tagCodigo,tipo,titulo,descricao,criadoPor).run()}catch(erro){console.error('Não foi possível registrar evento automático na timeline:',erro)}}
