const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=254)=>String(value??"").trim().slice(0,max);
const sqlNow=()=>new Date().toISOString().replace("T"," ").slice(0,19);
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function sessionToken(request){const jar={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();try{jar[key]=decodeURIComponent(part.slice(at+1).trim())}catch{jar[key]=part.slice(at+1).trim()}}for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function session(request,env){const token=sessionToken(request);if(!token)return null;return env.DB.prepare("SELECT email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(token),sqlNow()).first()}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return[...bytes].map(value=>value.toString(16).padStart(2,"0")).join("")}
async function setup(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS compartilhamentos_veterinarios(id INTEGER PRIMARY KEY AUTOINCREMENT,token_hash TEXT NOT NULL UNIQUE,tag_codigo TEXT NOT NULL,email_tutor TEXT NOT NULL,titulo TEXT NOT NULL DEFAULT 'Resumo veterinário',incluir_tutor INTEGER NOT NULL DEFAULT 1,incluir_cuidados INTEGER NOT NULL DEFAULT 1,incluir_medicamentos INTEGER NOT NULL DEFAULT 1,incluir_vacinas INTEGER NOT NULL DEFAULT 1,incluir_pesos INTEGER NOT NULL DEFAULT 1,incluir_agendamentos INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'ativo',acessos INTEGER NOT NULL DEFAULT 0,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expira_em TEXT NOT NULL,ultimo_acesso_em TEXT,revogado_em TEXT)`).run()}
async function auth(request,env){const current=await session(request,env);return current||json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401)}
async function owner(env,tag,email){return env.DB.prepare("SELECT id,nome FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,email).first()}
export async function onRequestGet({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100);if(!tag||!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const rows=await env.DB.prepare(`SELECT id,titulo,status,acessos,criado_em AS criadoEm,expira_em AS expiraEm,ultimo_acesso_em AS ultimoAcessoEm,CASE WHEN status='ativo' AND expira_em>CURRENT_TIMESTAMP THEN 1 ELSE 0 END AS ativo FROM compartilhamentos_veterinarios WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email_tutor)=LOWER(?) ORDER BY id DESC LIMIT 30`).bind(tag,current.email).all();return json({sucesso:true,compartilhamentos:rows.results||[]})}catch(error){console.error("Erro ao listar compartilhamentos:",error);return json({sucesso:false,mensagem:"Não foi possível carregar os links."},500)}}
export async function onRequestPost({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100),title=clean(body.titulo,100)||"Resumo veterinário",hours=[24,168,720].includes(Number(body.validadeHoras))?Number(body.validadeHoras):24;if(!tag||!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const fields=["tutor","cuidados","medicamentos","vacinas","pesos","agendamentos"],selected=fields.filter(field=>body[`incluir_${field}`]!==false);if(!selected.length)return json({sucesso:false,mensagem:"Escolha pelo menos uma informação para compartilhar."},400);const raw=randomToken(),hash=await sha(raw),expires=new Date(Date.now()+hours*3600000).toISOString().replace("T"," ").slice(0,19);await env.DB.prepare(`INSERT INTO compartilhamentos_veterinarios(token_hash,tag_codigo,email_tutor,titulo,incluir_tutor,incluir_cuidados,incluir_medicamentos,incluir_vacinas,incluir_pesos,incluir_agendamentos,expira_em) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(hash,tag,current.email,title,...fields.map(field=>selected.includes(field)?1:0),expires).run();return json({sucesso:true,mensagem:"Link seguro criado.",url:`${new URL(request.url).origin}/resumo-compartilhado.html?token=${raw}`,expiraEm:expires},201)}catch(error){console.error("Erro ao criar compartilhamento:",error);return json({sucesso:false,mensagem:"Não foi possível criar o link."},500)}}
export async function onRequestDelete({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag||!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Link não encontrado."},404);const result=await env.DB.prepare("UPDATE compartilhamentos_veterinarios SET status='revogado',revogado_em=CURRENT_TIMESTAMP WHERE id=? AND UPPER(tag_codigo)=UPPER(?) AND LOWER(email_tutor)=LOWER(?) AND status='ativo'").bind(id,tag,current.email).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Link já encerrado ou não encontrado."},404);return json({sucesso:true,mensagem:"Acesso revogado imediatamente."})}catch(error){return json({sucesso:false,mensagem:"Não foi possível revogar o link."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
