const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
function token(request){const jar={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();try{jar[key]=decodeURIComponent(part.slice(at+1).trim())}catch{jar[key]=part.slice(at+1).trim()}}for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
async function setup(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_despesas(id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,categoria TEXT NOT NULL,descricao TEXT NOT NULL,valor_centavos INTEGER NOT NULL,data_despesa TEXT NOT NULL,estabelecimento TEXT,forma_pagamento TEXT,observacoes TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function owner(env,tag,email){return env.DB.prepare("SELECT id,nome FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,email).first()}
async function auth(request,env){const current=await session(request,env);return current||json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401)}
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00Z`));
const categories=["consulta","medicamento","vacina","exame","alimentacao","higiene","acessorio","outro"];
export async function onRequestGet({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const url=new URL(request.url),tag=clean(url.searchParams.get("tagCodigo"),100),month=clean(url.searchParams.get("mes"),7);if(!tag||!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const filter=/^\d{4}-\d{2}$/.test(month)?month:"";const rows=await env.DB.prepare(`SELECT id,categoria,descricao,valor_centavos AS valorCentavos,data_despesa AS dataDespesa,estabelecimento,forma_pagamento AS formaPagamento,observacoes,criado_em AS criadoEm FROM pet_despesas WHERE UPPER(tag_codigo)=UPPER(?) AND (?='' OR substr(data_despesa,1,7)=?) ORDER BY date(data_despesa) DESC,id DESC LIMIT 300`).bind(tag,filter,filter).all();const totals=await env.DB.prepare(`SELECT COALESCE(SUM(valor_centavos),0) AS total,COALESCE(SUM(CASE WHEN substr(data_despesa,1,7)=strftime('%Y-%m','now','localtime') THEN valor_centavos ELSE 0 END),0) AS mesAtual FROM pet_despesas WHERE UPPER(tag_codigo)=UPPER(?)`).bind(tag).first();return json({sucesso:true,despesas:rows.results||[],totalCentavos:Number(totals?.total||0),mesAtualCentavos:Number(totals?.mesAtual||0),filtroMes:filter})}catch(error){console.error("despesas GET",error);return json({sucesso:false,mensagem:"Não foi possível carregar as despesas."},500)}}
export async function onRequestPost({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10)||null,tag=clean(body.tagCodigo,100),category=categories.includes(body.categoria)?body.categoria:"outro",description=clean(body.descricao,160),cents=Math.round(Number(body.valor)*100),date=clean(body.dataDespesa,10),place=clean(body.estabelecimento,160),payment=clean(body.formaPagamento,60),notes=clean(body.observacoes,500);if(!tag||!description||!Number.isInteger(cents)||cents<1||cents>100000000||!validDate(date))return json({sucesso:false,mensagem:"Informe descrição, valor e data válidos."},400);const pet=await owner(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);if(id){const result=await env.DB.prepare(`UPDATE pet_despesas SET categoria=?,descricao=?,valor_centavos=?,data_despesa=?,estabelecimento=?,forma_pagamento=?,observacoes=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND UPPER(tag_codigo)=UPPER(?)`).bind(category,description,cents,date,place||null,payment||null,notes||null,id,tag).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Despesa não encontrada."},404);return json({sucesso:true,mensagem:"Despesa atualizada."})}const result=await env.DB.prepare(`INSERT INTO pet_despesas(tag_codigo,categoria,descricao,valor_centavos,data_despesa,estabelecimento,forma_pagamento,observacoes) VALUES(?,?,?,?,?,?,?,?)`).bind(tag,category,description,cents,date,place||null,payment||null,notes||null).run();return json({sucesso:true,mensagem:`Despesa de ${pet.nome} registrada.`,id:result.meta?.last_row_id||null},201)}catch(error){console.error("despesas POST",error);return json({sucesso:false,mensagem:"Não foi possível salvar a despesa."},500)}}
export async function onRequestDelete({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag||!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Despesa não encontrada."},404);const result=await env.DB.prepare("DELETE FROM pet_despesas WHERE id=? AND UPPER(tag_codigo)=UPPER(?)").bind(id,tag).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Despesa não encontrada."},404);return json({sucesso:true,mensagem:"Despesa excluída."})}catch{return json({sucesso:false,mensagem:"Não foi possível excluir a despesa."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
