import { obterSessaoTutor, petPertenceAoTutor } from "../_lib/auth.js";

const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
async function setup(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_despesas(id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,categoria TEXT NOT NULL,descricao TEXT NOT NULL,valor_centavos INTEGER NOT NULL,data_despesa TEXT NOT NULL,estabelecimento TEXT,forma_pagamento TEXT,observacoes TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function auth(request,env){const current=await obterSessaoTutor(request,env);return current||json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401)}
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00Z`));
const categories=["consulta","medicamento","vacina","exame","alimentacao","higiene","acessorio","outro"];
export async function onRequestGet({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const url=new URL(request.url),tag=clean(url.searchParams.get("tagCodigo"),100),month=clean(url.searchParams.get("mes"),7);if(!tag||!await petPertenceAoTutor(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const filter=/^\d{4}-\d{2}$/.test(month)?month:"";const rows=await env.DB.prepare(`SELECT id,categoria,descricao,valor_centavos AS valorCentavos,data_despesa AS dataDespesa,estabelecimento,forma_pagamento AS formaPagamento,observacoes,criado_em AS criadoEm FROM pet_despesas WHERE UPPER(tag_codigo)=UPPER(?) ORDER BY date(data_despesa) DESC,id DESC LIMIT 300`).bind(tag).all();const filtradas=filter?rows.results.filter(item=>String(item.dataDespesa||'').slice(0,7)===filter):rows.results;const totals=await env.DB.prepare(`SELECT COALESCE(SUM(valor_centavos),0) AS total,COALESCE(SUM(CASE WHEN substr(data_despesa,1,7)=strftime('%Y-%m','now','localtime') THEN valor_centavos ELSE 0 END),0) AS mesAtual FROM pet_despesas WHERE UPPER(tag_codigo)=UPPER(?)`).bind(tag).first();return json({sucesso:true,despesas:filtradas||[],totalCentavos:Number(totals?.total||0),mesAtualCentavos:Number(totals?.mesAtual||0),filtroMes:filter})}catch(error){console.error("despesas GET",error);return json({sucesso:false,mensagem:"Não foi possível carregar as despesas."},500)}}
export async function onRequestPost({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10)||null,tag=clean(body.tagCodigo,100),category=categories.includes(body.categoria)?body.categoria:"outro",description=clean(body.descricao,160),cents=Math.round(Number(body.valor)*100),date=clean(body.dataDespesa,10),place=clean(body.estabelecimento,160),payment=clean(body.formaPagamento,60),notes=clean(body.observacoes,500);if(!tag||!description||!Number.isInteger(cents)||cents<1||cents>100000000||!validDate(date))return json({sucesso:false,mensagem:"Informe descrição, valor e data válidos."},400);const pet=await petPertenceAoTutor(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);if(id){const result=await env.DB.prepare(`UPDATE pet_despesas SET categoria=?,descricao=?,valor_centavos=?,data_despesa=?,estabelecimento=?,forma_pagamento=?,observacoes=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND UPPER(tag_codigo)=UPPER(?) AND EXISTS(SELECT 1 FROM pets p WHERE UPPER(p.tag_codigo)=UPPER(pet_despesas.tag_codigo) AND LOWER(p.email)=LOWER(?))`).bind(category,description,cents,date,place||null,payment||null,notes||null,id,tag,current.email).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Despesa não encontrada."},404);return json({sucesso:true,mensagem:"Despesa atualizada."})}const result=await env.DB.prepare(`INSERT INTO pet_despesas(tag_codigo,categoria,descricao,valor_centavos,data_despesa,estabelecimento,forma_pagamento,observacoes) VALUES(?,?,?,?,?,?,?,?)`).bind(tag,category,description,cents,date,place||null,payment||null,notes||null).run();return json({sucesso:true,mensagem:`Despesa de ${pet.nome||'pet'} registrada.`,id:result.meta?.last_row_id||null},201)}catch(error){console.error("despesas POST",error);return json({sucesso:false,mensagem:"Não foi possível salvar a despesa."},500)}}
export async function onRequestDelete({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await setup(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag||!await petPertenceAoTutor(env,tag,current.email))return json({sucesso:false,mensagem:"Despesa não encontrada."},404);const result=await env.DB.prepare(`DELETE FROM pet_despesas WHERE id=? AND UPPER(tag_codigo)=UPPER(?) AND EXISTS(SELECT 1 FROM pets p WHERE UPPER(p.tag_codigo)=UPPER(pet_despesas.tag_codigo) AND LOWER(p.email)=LOWER(?))`).bind(id,tag,current.email).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Despesa não encontrada."},404);return json({sucesso:true,mensagem:"Despesa excluída."})}catch(error){console.error("despesas DELETE",error);return json({sucesso:false,mensagem:"Não foi possível excluir a despesa."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
