function json(dados,status=200){return Response.json(dados,{status,headers:{"Cache-Control":"no-store"}})}
function cookie(request,nome){for(const p of(request.headers.get("Cookie")||"").split(";")){const[c,...v]=p.trim().split("=");if(c===nome)return decodeURIComponent(v.join("="))}return null}
async function hash(texto,algoritmo="SHA-256"){const b=await crypto.subtle.digest(algoritmo,new TextEncoder().encode(texto));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function sessao(request,env){const token=cookie(request,"orbitek_sessao");if(!token)return null;const s=await env.DB.prepare(`SELECT email,expira_em FROM sessoes_tutor WHERE token_hash=? LIMIT 1`).bind(await hash(token)).first();if(!s)return null;const n=Number(s.expira_em),d=Number.isFinite(n)&&n>0?n:Date.parse(s.expira_em);return Number.isFinite(d)&&Date.now()<=d?s:null}
async function petDoTutor(env,tag,email){return env.DB.prepare(`SELECT id,tag_codigo,foto_url FROM pets WHERE tag_codigo=? AND LOWER(email)=LOWER(?) LIMIT 1`).bind(tag,email).first()}
function tag(form){return String(form.get("tagCodigo")||"").trim().toUpperCase()}
export async function onRequestGet({request,env}){const s=await sessao(request,env);if(!s)return json({sucesso:false,autenticado:false},401);const codigo=String(new URL(request.url).searchParams.get("tag")||"").trim().toUpperCase(),pet=await petDoTutor(env,codigo,s.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado."},404);const extras=await env.DB.prepare(`SELECT id,url,ordem FROM pet_fotos WHERE tag_codigo=? ORDER BY ordem,id LIMIT 4`).bind(codigo).all();const fotos=[];if(pet.foto_url)fotos.push({id:null,url:pet.foto_url,principal:true});for(const f of extras.results||[])fotos.push({id:f.id,url:f.url,principal:false});return json({sucesso:true,fotos,limite:5})}
export async function onRequestPost({request,env}){try{const s=await sessao(request,env);if(!s)return json({sucesso:false,autenticado:false},401);const form=await request.formData(),codigo=tag(form),arquivo=form.get("foto"),pet=await petDoTutor(env,codigo,s.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado."},404);if(!arquivo||!['image/jpeg','image/png','image/webp'].includes(arquivo.type)||arquivo.size>5*1024*1024)return json({sucesso:false,mensagem:"Envie uma foto JPG, PNG ou WEBP de até 5 MB."},400);const total=await env.DB.prepare(`SELECT COUNT(*) AS total FROM pet_fotos WHERE tag_codigo=?`).bind(codigo).first();if(Number(total?.total||0)+(pet.foto_url?1:0)>=5)return json({sucesso:false,mensagem:"O limite de cinco fotos foi atingido."},409);const timestamp=Math.floor(Date.now()/1000),folder="orbitek-pets/galeria",publicId=`${codigo.toLowerCase()}-${timestamp}-${crypto.randomUUID().slice(0,8)}`,assinatura=await hash(`folder=${folder}&public_id=${publicId}&timestamp=${timestamp}${env.CLOUDINARY_API_SECRET}`,"SHA-1"),cloud=new FormData();cloud.append("file",arquivo);cloud.append("api_key",env.CLOUDINARY_API_KEY);cloud.append("timestamp",String(timestamp));cloud.append("signature",assinatura);cloud.append("folder",folder);cloud.append("public_id",publicId);const resposta=await fetch(`https://api.cloudinary.com/v1_1/${env.CLOUDINARY_CLOUD_NAME}/image/upload`,{method:"POST",body:cloud}),dados=await resposta.json();if(!resposta.ok||!dados.secure_url)return json({sucesso:false,mensagem:dados?.error?.message||"Não foi possível enviar a foto."},502);await env.DB.prepare(`INSERT INTO pet_fotos(tag_codigo,url,public_id,ordem) VALUES(?,?,?,?)`).bind(codigo,dados.secure_url,dados.public_id,Number(total?.total||0)+1).run();return json({sucesso:true,mensagem:"Foto adicionada à galeria."},201)}catch(erro){console.error("Erro na galeria:",erro);return json({sucesso:false,mensagem:"Não foi possível salvar a foto."},500)}}
export async function onRequestDelete({request,env}){const s=await sessao(request,env);if(!s)return json({sucesso:false,autenticado:false},401);const corpo=await request.json().catch(()=>({})),id=Number(corpo.id);if(!Number.isInteger(id)||id<1)return json({sucesso:false,mensagem:"Foto inválida."},400);const foto=await env.DB.prepare(`SELECT f.id FROM pet_fotos f JOIN pets p ON p.tag_codigo=f.tag_codigo WHERE f.id=? AND LOWER(p.email)=LOWER(?)`).bind(id,s.email).first();if(!foto)return json({sucesso:false,mensagem:"Foto não encontrada."},404);await env.DB.prepare(`DELETE FROM pet_fotos WHERE id=?`).bind(id).run();return json({sucesso:true,mensagem:"Foto removida."})}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
