const JSON_HEADERS={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const reply=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}});
const clean=(value,max=1000)=>String(value??"").trim().slice(0,max);
function cookies(request){const result={};for(const part of (request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();if(!key)continue;try{result[key]=decodeURIComponent(part.slice(at+1).trim())}catch{result[key]=part.slice(at+1).trim()}}return result}
function token(request){const jar=cookies(request);for(const key of ["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return ""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT id,email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
async function owns(env,tag,email){return env.DB.prepare("SELECT id,nome FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,email).first()}
function date(value){const result=clean(value,10);if(!result)return "";if(!/^\d{4}-\d{2}-\d{2}$/.test(result))return null;const [y,m,d]=result.split("-").map(Number),test=new Date(Date.UTC(y,m-1,d));return test.getUTCFullYear()===y&&test.getUTCMonth()===m-1&&test.getUTCDate()===d?result:null}
async function authenticate(request,env){const current=await session(request,env);return current||reply({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou. Entre novamente."},401)}

export async function onRequestGet({request,env}){
  try{const current=await authenticate(request,env);if(current instanceof Response)return current;const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100);if(!tag)return reply({sucesso:false,mensagem:"Código da tag não informado."},400);if(!await owns(env,tag,current.email))return reply({sucesso:false,mensagem:"Pet não encontrado ou sem permissão de acesso."},403);const rows=await env.DB.prepare(`SELECT id,tag_codigo AS tagCodigo,nome,dosagem,frequencia,horarios,data_inicio AS dataInicio,data_fim AS dataFim,veterinario,observacoes,ativo,criado_em AS criadoEm,atualizado_em AS atualizadoEm FROM pet_medicamentos WHERE UPPER(tag_codigo)=UPPER(?) ORDER BY ativo DESC,CASE WHEN data_fim IS NULL OR data_fim='' THEN 1 ELSE 0 END DESC,date(data_fim) ASC,id DESC`).bind(tag).all();return reply({sucesso:true,medicamentos:rows.results||[]})}catch(error){console.error("Erro em /api/medicamentos GET:",error);return reply({sucesso:false,mensagem:error.message||"Erro ao carregar medicamentos."},500)}
}

export async function onRequestPost({request,env}){
  try{const current=await authenticate(request,env);if(current instanceof Response)return current;const body=await request.json().catch(()=>({}));const id=body.id?Number.parseInt(body.id,10):null,tag=clean(body.tagCodigo,100),nome=clean(body.nome,120),dosagem=clean(body.dosagem,80),frequencia=clean(body.frequencia,120),horarios=clean(body.horarios,120),inicio=date(body.dataInicio),fim=date(body.dataFim),veterinario=clean(body.veterinario,120),observacoes=clean(body.observacoes,1000),ativo=body.ativo===false||body.ativo===0?0:1;if((body.id&&!id)||!tag||!nome||!frequencia||!inicio)return reply({sucesso:false,mensagem:"Informe medicamento, frequência e data de início."},400);if(inicio===null||fim===null)return reply({sucesso:false,mensagem:"Uma das datas é inválida."},400);if(fim&&fim<inicio)return reply({sucesso:false,mensagem:"A data final não pode ser anterior ao início."},400);if(!await owns(env,tag,current.email))return reply({sucesso:false,mensagem:"Pet não encontrado ou sem permissão de acesso."},403);
    const detail=[dosagem&&`Dosagem: ${dosagem}`,frequencia&&`Frequência: ${frequencia}`,horarios&&`Horários: ${horarios}`,fim&&`Até: ${fim}`].filter(Boolean).join(" • ");
    if(id){const found=await env.DB.prepare(`SELECT m.id FROM pet_medicamentos m INNER JOIN pets p ON UPPER(p.tag_codigo)=UPPER(m.tag_codigo) WHERE m.id=? AND UPPER(m.tag_codigo)=UPPER(?) AND LOWER(p.email)=LOWER(?) LIMIT 1`).bind(id,tag,current.email).first();if(!found)return reply({sucesso:false,mensagem:"Medicamento não encontrado."},404);await env.DB.batch([env.DB.prepare(`UPDATE pet_medicamentos SET nome=?,dosagem=?,frequencia=?,horarios=?,data_inicio=?,data_fim=NULLIF(?,''),veterinario=?,observacoes=?,ativo=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=? AND UPPER(tag_codigo)=UPPER(?)`).bind(nome,dosagem,frequencia,horarios,inicio,fim,veterinario,observacoes,ativo,id,tag),env.DB.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,?,?,?,?,1,?)`).bind(tag,"medicamento",`Medicamento ${nome} atualizado`,detail||null,new Date().toISOString(),current.email)]);return reply({sucesso:true,mensagem:"Medicamento atualizado com sucesso.",id})}
    const result=await env.DB.batch([env.DB.prepare(`INSERT INTO pet_medicamentos(tag_codigo,nome,dosagem,frequencia,horarios,data_inicio,data_fim,veterinario,observacoes,ativo) VALUES(?,?,?,?,?,?,NULLIF(?,''),?,?,?)`).bind(tag,nome,dosagem,frequencia,horarios,inicio,fim,veterinario,observacoes,ativo),env.DB.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,?,?,?,?,1,?)`).bind(tag,"medicamento",`Medicamento ${nome} iniciado`,detail||null,`${inicio}T12:00:00.000Z`,current.email)]);return reply({sucesso:true,mensagem:"Medicamento cadastrado e adicionado à timeline.",id:result[0]?.meta?.last_row_id||null},201)
  }catch(error){console.error("Erro em /api/medicamentos POST:",error);return reply({sucesso:false,mensagem:error.message||"Erro ao salvar medicamento."},500)}
}

export async function onRequestDelete({request,env}){
  try{const current=await authenticate(request,env);if(current instanceof Response)return current;const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag)return reply({sucesso:false,mensagem:"Medicamento e tag são obrigatórios."},400);const found=await env.DB.prepare(`SELECT m.id FROM pet_medicamentos m INNER JOIN pets p ON UPPER(p.tag_codigo)=UPPER(m.tag_codigo) WHERE m.id=? AND UPPER(m.tag_codigo)=UPPER(?) AND LOWER(p.email)=LOWER(?) LIMIT 1`).bind(id,tag,current.email).first();if(!found)return reply({sucesso:false,mensagem:"Medicamento não encontrado."},404);await env.DB.prepare("DELETE FROM pet_medicamentos WHERE id=? AND UPPER(tag_codigo)=UPPER(?)").bind(id,tag).run();return reply({sucesso:true,mensagem:"Medicamento excluído com sucesso."})}catch(error){console.error("Erro em /api/medicamentos DELETE:",error);return reply({sucesso:false,mensagem:error.message||"Erro ao excluir medicamento."},500)}
}

export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return reply({sucesso:false,mensagem:"Método não permitido."},405,{Allow:"GET, POST, DELETE"})}
