const HEADERS={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...HEADERS,...extra}});
const clean=(value,max=1000)=>String(value??"").trim().slice(0,max);
function cookie(request){const jar={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();try{jar[key]=decodeURIComponent(part.slice(at+1).trim())}catch{jar[key]=part.slice(at+1).trim()}}for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return ""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=cookie(request);if(!value)return null;return env.DB.prepare("SELECT email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
const validDate=(value)=>/^\d{4}-\d{2}-\d{2}$/.test(value);
const validTime=(value)=>/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value);
const times=(value)=>[...new Set((String(value||"").match(/(?:[01]\d|2[0-3]):[0-5]\d/g)||[]))].sort();
async function ownedPet(env,tag,email){return env.DB.prepare("SELECT id FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,email).first()}

export async function onRequestGet({request,env}){
  try{const current=await session(request,env);if(!current)return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou. Entre novamente."},401);const url=new URL(request.url),tag=clean(url.searchParams.get("tagCodigo"),100),today=clean(url.searchParams.get("data"),10),now=clean(url.searchParams.get("hora"),5);if(!tag||!validDate(today)||!validTime(now))return json({sucesso:false,mensagem:"Tag, data e hora local válidas são obrigatórias."},400);if(!await ownedPet(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);
    const medicines=await env.DB.prepare(`SELECT id,nome,horarios,data_inicio,data_fim,ativo FROM pet_medicamentos WHERE UPPER(tag_codigo)=UPPER(?) AND ativo=1 AND date(data_inicio)<=date(?) AND (data_fim IS NULL OR data_fim='' OR date(data_fim)>=date(?))`).bind(tag,today,today).all();const commands=[];
    for(const med of medicines.results||[])for(const time of times(med.horarios)){const scheduled=`${today}T${time}:00`;commands.push(env.DB.prepare(`INSERT OR IGNORE INTO medicamento_doses(medicamento_id,tag_codigo,prevista_em) VALUES(?,?,?)`).bind(med.id,tag,scheduled));if(time<=now){const window=`dose:${med.id}:${today}:${time}`;commands.push(env.DB.prepare(`INSERT OR IGNORE INTO notificacoes_tutor(email,tag_codigo,tipo,janela,titulo,descricao,url) SELECT ?,?,'medicamento',?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM medicamento_doses WHERE medicamento_id=? AND prevista_em=? AND status IN ('administrada','ignorada'))`).bind(current.email,tag,window,`Hora do medicamento ${med.nome}`,`Dose prevista para ${time}. Confirme no painel se ela foi administrada.`,`/tutor?medicamentos=${encodeURIComponent(tag)}`,med.id,scheduled))}}
    if(commands.length)await env.DB.batch(commands);const result=await env.DB.prepare(`SELECT d.id,d.medicamento_id AS medicamentoId,m.nome AS medicamento,d.prevista_em AS previstaEm,d.status,d.registrada_em AS registradaEm,d.observacoes FROM medicamento_doses d INNER JOIN pet_medicamentos m ON m.id=d.medicamento_id WHERE UPPER(d.tag_codigo)=UPPER(?) AND datetime(d.prevista_em)>=datetime(?,'-30 days') ORDER BY datetime(d.prevista_em) DESC,d.id DESC`).bind(tag,`${today}T00:00:00`).all();return json({sucesso:true,doses:result.results||[]})
  }catch(error){console.error("Erro em /api/medicamento-doses GET:",error);return json({sucesso:false,mensagem:error.message||"Erro ao carregar as doses."},500)}
}

export async function onRequestPost({request,env}){
  try{const current=await session(request,env);if(!current)return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou. Entre novamente."},401);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100),id=Number.parseInt(body.medicamentoId,10),scheduled=clean(body.previstaEm,19),status=clean(body.status,20),notes=clean(body.observacoes,500);if(!tag||!id||!/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:00/.test(scheduled)||!["administrada","ignorada"].includes(status))return json({sucesso:false,mensagem:"Dados da dose são inválidos."},400);const medicine=await env.DB.prepare(`SELECT m.id,m.nome FROM pet_medicamentos m INNER JOIN pets p ON UPPER(p.tag_codigo)=UPPER(m.tag_codigo) WHERE m.id=? AND UPPER(m.tag_codigo)=UPPER(?) AND LOWER(p.email)=LOWER(?) LIMIT 1`).bind(id,tag,current.email).first();if(!medicine)return json({sucesso:false,mensagem:"Medicamento não encontrado ou sem permissão."},404);await env.DB.prepare(`INSERT INTO medicamento_doses(medicamento_id,tag_codigo,prevista_em,status,registrada_em,observacoes) VALUES(?,?,?,?,CURRENT_TIMESTAMP,?) ON CONFLICT(medicamento_id,prevista_em) DO UPDATE SET status=excluded.status,registrada_em=CURRENT_TIMESTAMP,observacoes=excluded.observacoes`).bind(id,tag,scheduled,status,notes).run();return json({sucesso:true,mensagem:status==="administrada"?"Dose marcada como administrada.":"Dose marcada como ignorada."})
  }catch(error){console.error("Erro em /api/medicamento-doses POST:",error);return json({sucesso:false,mensagem:error.message||"Erro ao registrar a dose."},500)}
}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);return json({sucesso:false,mensagem:"Método não permitido."},405,{Allow:"GET, POST"})}
