const HEADERS={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:HEADERS});
const clean=(value,max=600)=>String(value??"").trim().slice(0,max);
const integer=(value,min,max,fallback)=>{const parsed=Number.parseInt(value,10);return Number.isFinite(parsed)?Math.min(max,Math.max(min,parsed)):fallback};
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function sessionToken(request){const jar={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at>0)jar[part.slice(0,at).trim()]=decodeURIComponent(part.slice(at+1).trim())}for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function session(request,env){const value=sessionToken(request);if(!value)return null;return env.DB.prepare("SELECT email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),Date.now()).first()}
async function catOwner(env,tag,email){return env.DB.prepare("SELECT nome,especie,perdido FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) AND LOWER(especie) IN ('gato','felino','felina') LIMIT 1").bind(tag,email).first()}
async function setup(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_modo_gato(tag_codigo TEXT PRIMARY KEY,acesso_rua TEXT NOT NULL DEFAULT 'nao',moradia TEXT NOT NULL DEFAULT 'apartamento',convivencia TEXT NOT NULL DEFAULT 'sozinho',quantidade_gatos INTEGER NOT NULL DEFAULT 1,castrado INTEGER NOT NULL DEFAULT 0,telas_protecao INTEGER NOT NULL DEFAULT 0,microchip INTEGER NOT NULL DEFAULT 0,caixas_areia INTEGER NOT NULL DEFAULT 1,pontos_agua INTEGER NOT NULL DEFAULT 1,observacoes TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
const defaultProfile=()=>({acessoRua:"nao",moradia:"apartamento",convivencia:"sozinho",quantidadeGatos:1,castrado:false,telasProtecao:false,microchip:false,caixasAreia:1,pontosAgua:1,observacoes:""});
function profile(row){if(!row)return defaultProfile();return{acessoRua:row.acesso_rua,moradia:row.moradia,convivencia:row.convivencia,quantidadeGatos:Number(row.quantidade_gatos),castrado:Number(row.castrado)===1,telasProtecao:Number(row.telas_protecao)===1,microchip:Number(row.microchip)===1,caixasAreia:Number(row.caixas_areia),pontosAgua:Number(row.pontos_agua),observacoes:row.observacoes||""}}
function recommendations(item){const list=[];if(item.acessoRua==="livre")list.push({nivel:"atencao",icone:"🏠",titulo:"Reduza saídas sem supervisão",texto:"O acesso livre aumenta riscos de fuga, atropelamento e contato com doenças. Prefira ambiente protegido ou saídas supervisionadas."});else if(item.acessoRua==="supervisionado")list.push({nivel:"bom",icone:"🦮",titulo:"Mantenha a supervisão",texto:"Use contenção apropriada e confira a identificação antes de cada saída."});else list.push({nivel:"bom",icone:"🏡",titulo:"Ambiente interno protegido",texto:"Enriquecimento, esconderijos e locais altos ajudam a tornar a vida dentro de casa mais interessante."});if(!item.telasProtecao)list.push({nivel:"atencao",icone:"🪟",titulo:"Proteja janelas e rotas de fuga",texto:"Avalie telas adequadas em janelas, sacadas, portões e outros pontos de saída."});if(!item.castrado)list.push({nivel:"informativo",icone:"🩺",titulo:"Converse sobre castração",texto:"Procure um médico-veterinário para avaliar o momento e a conduta apropriados para este gato."});if(!item.microchip)list.push({nivel:"informativo",icone:"🔎",titulo:"Reforce a identificação",texto:"A tag BIRX fica visível na coleira. O microchip pode oferecer uma identificação complementar permanente."});const ideal=Math.min(40,item.quantidadeGatos+1);if(item.caixasAreia<ideal)list.push({nivel:"atencao",icone:"🧺",titulo:"Revise as caixas de areia",texto:`Para ${item.quantidadeGatos} gato${item.quantidadeGatos===1?"":"s"}, uma referência comum é oferecer ${ideal} caixas, distribuídas em locais tranquilos.`});else list.push({nivel:"bom",icone:"🧺",titulo:"Boa distribuição de caixas",texto:"Mantenha a limpeza frequente e observe mudanças no uso das caixas."});if(item.pontosAgua<2)list.push({nivel:"informativo",icone:"💧",titulo:"Ofereça mais pontos de água",texto:"Distribua recipientes em locais diferentes e afastados da caixa de areia. Observe a preferência do gato."});list.push({nivel:"bom",icone:"🪶",titulo:"Brincadeira e enriquecimento",texto:"Inclua atividades de caça simulada, arranhadores, esconderijos e locais elevados na rotina."});return list}
const reminders=[{id:"caixa",icone:"🧺",tipo:"higiene",titulo:"Higienizar caixas de areia",descricao:"Retirar resíduos e observar alterações de uso.",horarios:"08:00,20:00"},{id:"agua",icone:"💧",tipo:"higiene",titulo:"Renovar água",descricao:"Higienizar recipientes e oferecer água fresca.",horarios:"08:00,18:00"},{id:"brincadeira",icone:"🪶",tipo:"atividade",titulo:"Brincadeira e enriquecimento",descricao:"Reservar um momento para atividade e interação segura.",horarios:"19:00"}];
async function getData(env,tag,pet){const row=await env.DB.prepare("SELECT * FROM pet_modo_gato WHERE UPPER(tag_codigo)=UPPER(?) LIMIT 1").bind(tag).first(),item=profile(row);return{sucesso:true,pet:{nome:pet.nome,perdido:Number(pet.perdido)===1},perfil:item,configurado:Boolean(row),recomendacoes:recommendations(item),lembretesSugeridos:reminders}}
export async function onRequestGet({request,env}){try{const current=await session(request,env);if(!current)return json({sucesso:false,autenticado:false},401);await setup(env);const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100),pet=tag&&await catOwner(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"O Modo Gato está disponível apenas para gatos da sua conta."},403);return json(await getData(env,tag,pet))}catch(error){console.error("modo-gato GET",error);return json({sucesso:false,mensagem:"Não foi possível carregar o Modo Gato."},500)}}
export async function onRequestPost({request,env}){try{const current=await session(request,env);if(!current)return json({sucesso:false,autenticado:false},401);await setup(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100),pet=tag&&await catOwner(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"Gato não encontrado ou sem permissão."},403);const access=["nao","supervisionado","livre"].includes(body.acessoRua)?body.acessoRua:"nao",home=["apartamento","casa","casa_quintal","outro"].includes(body.moradia)?body.moradia:"outro",company=["sozinho","gatos","caes","mista"].includes(body.convivencia)?body.convivencia:"sozinho",cats=integer(body.quantidadeGatos,1,30,1),litter=integer(body.caixasAreia,0,40,0),water=integer(body.pontosAgua,0,40,0),neutered=body.castrado?1:0,screens=body.telasProtecao?1:0,microchip=body.microchip?1:0,notes=clean(body.observacoes);await env.DB.prepare(`INSERT INTO pet_modo_gato(tag_codigo,acesso_rua,moradia,convivencia,quantidade_gatos,castrado,telas_protecao,microchip,caixas_areia,pontos_agua,observacoes) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(tag_codigo) DO UPDATE SET acesso_rua=excluded.acesso_rua,moradia=excluded.moradia,convivencia=excluded.convivencia,quantidade_gatos=excluded.quantidade_gatos,castrado=excluded.castrado,telas_protecao=excluded.telas_protecao,microchip=excluded.microchip,caixas_areia=excluded.caixas_areia,pontos_agua=excluded.pontos_agua,observacoes=excluded.observacoes,atualizado_em=CURRENT_TIMESTAMP`).bind(tag,access,home,company,cats,neutered,screens,microchip,litter,water,notes||null).run();return json({...await getData(env,tag,pet),mensagem:`Modo Gato de ${pet.nome} atualizado.`})}catch(error){console.error("modo-gato POST",error);return json({sucesso:false,mensagem:"Não foi possível salvar o perfil felino."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
