const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=UTF-8","Cache-Control":"private, max-age=300"}});
function token(request){const jar={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();try{jar[key]=decodeURIComponent(part.slice(at+1).trim())}catch{jar[key]=part.slice(at+1).trim()}}for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return ""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
function distance(a,b,c,d){const rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,lat1=a*rad,lat2=c*rad,h=Math.sin(x/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(y/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function address(tags){return[tags["addr:street"],tags["addr:housenumber"],tags["addr:suburb"],tags["addr:city"]].filter(Boolean).join(", ")}
async function geocode(endereco){const params=new URLSearchParams({q:endereco,format:"jsonv2",limit:"1",countrycodes:"br",addressdetails:"1"});const response=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{headers:{"User-Agent":"OrbitekPets/1.0 contato@orbitekoficial.com.br","Accept-Language":"pt-BR"}});if(!response.ok)return null;const result=await response.json();if(!result?.length)return null;return{latitude:Number(result[0].lat),longitude:Number(result[0].lon),enderecoFormatado:result[0].display_name}}
async function overpass(query){const body=`data=${encodeURIComponent(query)}`;for(const endpoint of["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter"]){try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded","User-Agent":"OrbitekPets/1.0 contato@orbitekoficial.com.br"},body});if(response.ok)return response.json()}catch{}}return null}
export async function onRequestGet({request,env}){try{if(!await session(request,env))return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou. Entre novamente."},401);const url=new URL(request.url),endereco=String(url.searchParams.get("endereco")||"").trim().slice(0,240),tipo=url.searchParams.get("tipo")==="clinicas"?"clinicas":"compras",raio=[5000,10000,20000].includes(Number(url.searchParams.get("raio")))?Number(url.searchParams.get("raio")):10000;if(endereco.length<8)return json({sucesso:false,mensagem:"Informe um endereço completo, com rua, número, cidade e estado."},400);const origin=await geocode(endereco);if(!origin||!Number.isFinite(origin.latitude)||!Number.isFinite(origin.longitude))return json({sucesso:false,mensagem:"Não encontramos esse endereço. Confira rua, número, cidade e estado."},404);const{latitude:lat,longitude:lng}=origin,filters=tipo==="clinicas"?`nwr(around:${raio},${lat},${lng})[amenity=veterinary];`:`nwr(around:${raio},${lat},${lng})[shop=pet];nwr(around:${raio},${lat},${lng})[shop=pet_products];nwr(around:${raio},${lat},${lng})[amenity=veterinary_pharmacy];nwr(around:${raio},${lat},${lng})[amenity=veterinary];`,data=await overpass(`[out:json][timeout:20];(${filters});out center tags;`);if(!data)return json({sucesso:false,mensagem:"O serviço de locais próximos está temporariamente indisponível."},503);const seen=new Set(),places=[];for(const item of data.elements||[]){const itemLat=Number(item.lat??item.center?.lat),itemLng=Number(item.lon??item.center?.lon),tags=item.tags||{},name=String(tags.name||tags.brand||"").trim();if(!name||!Number.isFinite(itemLat)||!Number.isFinite(itemLng))continue;const key=`${name.toLowerCase()}-${itemLat.toFixed(4)}-${itemLng.toFixed(4)}`;if(seen.has(key))continue;seen.add(key);const kind=tags.amenity==="veterinary_pharmacy"?"Farmácia veterinária":tags.shop==="pet"||tags.shop==="pet_products"?"Pet shop":tags.emergency==="yes"?"Clínica veterinária • Emergência":"Clínica veterinária";places.push({id:key,nome:name,tipo:kind,emergencia:tags.emergency==="yes"||/24\/7/.test(tags.opening_hours||""),latitude:itemLat,longitude:itemLng,distancia:distance(lat,lng,itemLat,itemLng),endereco:address(tags),telefone:tags.phone||tags["contact:phone"]||"",site:tags.website||tags["contact:website"]||"",horario:tags.opening_hours||""})}places.sort((a,b)=>a.distancia-b.distancia);return json({sucesso:true,locais:places.slice(0,30),origem:"OpenStreetMap",centro:{latitude:lat,longitude:lng,endereco:origin.enderecoFormatado},tipo,raio})}catch(error){console.error("Erro em /api/onde-comprar:",error);return json({sucesso:false,mensagem:"Não foi possível buscar locais próximos."},500)}}
export async function onRequest(context){if(context.request.method!=="GET")return json({sucesso:false,mensagem:"Método não permitido."},405);return onRequestGet(context)}
