const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"}});
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
async function sha(value){const data=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(data)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function sessionToken(request){const item=(request.headers.get("Cookie")||"").split(";").map(value=>value.trim()).find(value=>value.startsWith("birx_partner_session="));return item?decodeURIComponent(item.split("=").slice(1).join("=")):""}
async function session(request,env){const raw=sessionToken(request);if(!raw)return null;return env.DB.prepare(`SELECT p.id,p.nome,p.email,p.whatsapp,p.cidade,p.estado FROM parceiro_sessoes s INNER JOIN parceiros p ON p.id=s.parceiro_id WHERE s.token_hash=? AND s.expira_em>CURRENT_TIMESTAMP AND p.status='ativo' LIMIT 1`).bind(await sha(raw)).first()}
async function stock(env,id){const result=await env.DB.prepare(`SELECT e.tag_codigo AS codigo,CASE WHEN t.ativada=1 THEN 'ativada' ELSE e.status END AS status,t.modelo,t.lote,e.recebido_em AS recebidoEm,e.vendido_em AS vendidoEm FROM parceiro_estoque e INNER JOIN tags t ON UPPER(t.codigo)=UPPER(e.tag_codigo) WHERE e.parceiro_id=? ORDER BY e.id DESC LIMIT 300`).bind(id).all();return result.results||[]}
export async function onRequestGet({request,env}){const partner=await session(request,env);if(!partner)return json({sucesso:false,autenticado:false,mensagem:"Entre novamente no Painel do Parceiro."},401);try{const tags=await stock(env,partner.id),summary={total:tags.length,estoque:tags.filter(tag=>tag.status==="estoque").length,vendidas:tags.filter(tag=>tag.status==="vendida").length,ativadas:tags.filter(tag=>tag.status==="ativada").length};return json({sucesso:true,parceiro:partner,resumo:summary,tags})}catch(error){console.error("parceiro GET",error);return json({sucesso:false,mensagem:"Não foi possível carregar o estoque."},500)}}
export async function onRequestPost({request,env}){const partner=await session(request,env);if(!partner)return json({sucesso:false,autenticado:false,mensagem:"Entre novamente no Painel do Parceiro."},401);try{const body=await request.json().catch(()=>({})),action=clean(body.acao,30),code=clean(body.codigo,60).toUpperCase();if(action!=="venda"||!code)return json({sucesso:false,mensagem:"Ação inválida."},400);const item=await env.DB.prepare(`SELECT e.id,e.status,t.ativada,t.bloqueada FROM parceiro_estoque e INNER JOIN tags t ON UPPER(t.codigo)=UPPER(e.tag_codigo) WHERE e.parceiro_id=? AND UPPER(e.tag_codigo)=UPPER(?) LIMIT 1`).bind(partner.id,code).first();if(!item)return json({sucesso:false,mensagem:"Esta tag não pertence ao estoque do parceiro."},404);if(Number(item.bloqueada)===1)return json({sucesso:false,mensagem:"Esta tag está bloqueada. Fale com a BIRX."},409);if(Number(item.ativada)===1)return json({sucesso:false,mensagem:"Esta tag já foi ativada."},409);if(item.status!=="estoque")return json({sucesso:false,mensagem:"Esta venda já foi registrada."},409);await env.DB.batch([env.DB.prepare("UPDATE parceiro_estoque SET status='vendida',vendido_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=?").bind(item.id),env.DB.prepare("INSERT OR IGNORE INTO parceiro_vendas(parceiro_id,tag_codigo,observacoes) VALUES(?,?,?)").bind(partner.id,code,clean(body.observacoes,300)),env.DB.prepare("UPDATE tags SET preparo_status='vendida',vendida_em=CURRENT_TIMESTAMP WHERE UPPER(codigo)=UPPER(?) AND ativada=0").bind(code)]);return json({sucesso:true,mensagem:`Venda da tag ${code} registrada.`,urlAtivacao:`/q/${encodeURIComponent(code)}`})}catch(error){console.error("parceiro POST",error);return json({sucesso:false,mensagem:"Não foi possível registrar a venda."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);return json({sucesso:false},405)}

