const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store",...headers}});
const clean=(value,max=180)=>String(value??"").trim().slice(0,max);
async function sha(value){const data=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(data)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function token(){const bytes=crypto.getRandomValues(new Uint8Array(32));return[...bytes].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function cookie(value,maxAge=604800){return`birx_partner_session=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
export async function onRequestPost({request,env}){try{const body=await request.json().catch(()=>({})),mail=clean(body.email).toLowerCase(),code=clean(body.codigo,80).toUpperCase();if(!/^\S+@\S+\.\S+$/.test(mail)||code.length<8)return json({sucesso:false,mensagem:"Informe e-mail e código de acesso."},400);const partner=await env.DB.prepare("SELECT id,nome,codigo_acesso_hash AS hash FROM parceiros WHERE LOWER(email)=LOWER(?) AND status='ativo' LIMIT 1").bind(mail).first();if(!partner||!partner.hash||(await sha(code))!==partner.hash)return json({sucesso:false,mensagem:"E-mail ou código de acesso inválido."},401);const raw=token(),expires=new Date(Date.now()+7*86400000).toISOString().replace("T"," ").slice(0,19);await env.DB.prepare("INSERT INTO parceiro_sessoes(parceiro_id,token_hash,expira_em) VALUES(?,?,?)").bind(partner.id,await sha(raw),expires).run();return json({sucesso:true,mensagem:"Acesso autorizado.",parceiro:{nome:partner.nome}},200,{"Set-Cookie":cookie(raw)})}catch(error){console.error("parceiro-login",error);return json({sucesso:false,mensagem:"Não foi possível entrar no painel."},500)}}
export async function onRequestDelete({request,env}){const value=(request.headers.get("Cookie")||"").split(";").map(item=>item.trim()).find(item=>item.startsWith("birx_partner_session="))?.split("=").slice(1).join("=")||"";if(value)await env.DB.prepare("DELETE FROM parceiro_sessoes WHERE token_hash=?").bind(await sha(decodeURIComponent(value))).run();return json({sucesso:true},200,{"Set-Cookie":cookie("",0)})}
export async function onRequest(context){if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false},405)}

