const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
function token(request){const jar={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();try{jar[key]=decodeURIComponent(part.slice(at+1).trim())}catch{jar[key]=part.slice(at+1).trim()}}for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_pesos(id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,peso_kg REAL NOT NULL,data_medicao TEXT NOT NULL,observacoes TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function owner(env,tag,email){return env.DB.prepare("SELECT id,nome FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,email).first()}
async function auth(request,env){const current=await session(request,env);return current||json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401)}
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00Z`));
export async function onRequestGet({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await ensure(env);const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100);if(!tag)return json({sucesso:false,mensagem:"Tag não informada."},400);if(!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const rows=await env.DB.prepare(`SELECT id,peso_kg AS pesoKg,data_medicao AS dataMedicao,observacoes,criado_em AS criadoEm FROM pet_pesos WHERE UPPER(tag_codigo)=UPPER(?) ORDER BY date(data_medicao) DESC,id DESC LIMIT 100`).bind(tag).all();return json({sucesso:true,pesos:rows.results||[]})}catch(error){console.error("Erro ao listar pesos:",error);return json({sucesso:false,mensagem:"Não foi possível carregar o histórico de peso."},500)}}
export async function onRequestPost({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await ensure(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100),weight=Number(body.pesoKg),date=clean(body.dataMedicao,10),notes=clean(body.observacoes,500);if(!tag||!Number.isFinite(weight)||weight<0.1||weight>300||!validDate(date))return json({sucesso:false,mensagem:"Informe um peso entre 0,1 e 300 kg e uma data válida."},400);const pet=await owner(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const result=await env.DB.batch([env.DB.prepare("INSERT INTO pet_pesos(tag_codigo,peso_kg,data_medicao,observacoes) VALUES(?,?,?,?)").bind(tag,Math.round(weight*100)/100,date,notes||null),env.DB.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,'peso',?,?,?,1,?)`).bind(tag,`Peso registrado: ${String(Math.round(weight*100)/100).replace(".",",")} kg`,notes||null,`${date}T12:00:00.000Z`,current.email)]);return json({sucesso:true,mensagem:`Peso de ${pet.nome} registrado.`,id:result[0]?.meta?.last_row_id||null},201)}catch(error){console.error("Erro ao salvar peso:",error);return json({sucesso:false,mensagem:"Não foi possível registrar o peso."},500)}}
export async function onRequestDelete({request,env}){try{const current=await auth(request,env);if(current instanceof Response)return current;await ensure(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag)return json({sucesso:false,mensagem:"Registro inválido."},400);if(!await owner(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const result=await env.DB.prepare("DELETE FROM pet_pesos WHERE id=? AND UPPER(tag_codigo)=UPPER(?)").bind(id,tag).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Registro não encontrado."},404);return json({sucesso:true,mensagem:"Medição excluída."})}catch(error){console.error("Erro ao excluir peso:",error);return json({sucesso:false,mensagem:"Não foi possível excluir a medição."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
