import { obterSessaoTutor, petPertenceAoTutor } from "../_lib/auth.js";
const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=500)=>String(value??"").trim().slice(0,max);
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pet_pesos(id INTEGER PRIMARY KEY AUTOINCREMENT,tag_codigo TEXT NOT NULL,peso_kg REAL NOT NULL,data_medicao TEXT NOT NULL,observacoes TEXT,criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00Z`));
export async function onRequestGet({request,env}){try{const current=await obterSessaoTutor(request,env);if(!current)return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401);await ensure(env);const tag=clean(new URL(request.url).searchParams.get("tagCodigo"),100);if(!tag)return json({sucesso:false,mensagem:"Tag não informada."},400);if(!await petPertenceAoTutor(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const rows=await env.DB.prepare(`SELECT id,peso_kg AS pesoKg,data_medicao AS dataMedicao,observacoes,criado_em AS criadoEm FROM pet_pesos WHERE UPPER(tag_codigo)=UPPER(?) ORDER BY date(data_medicao) DESC,id DESC LIMIT 100`).bind(tag).all();return json({sucesso:true,pesos:rows.results||[]})}catch(error){console.error("Erro ao listar pesos:",error);return json({sucesso:false,mensagem:"Não foi possível carregar o histórico de peso."},500)}}
export async function onRequestPost({request,env}){try{const current=await obterSessaoTutor(request,env);if(!current)return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401);await ensure(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100),weight=Number(body.pesoKg),date=clean(body.dataMedicao,10),notes=clean(body.observacoes,500);if(!tag||!Number.isFinite(weight)||weight<0.1||weight>300||!validDate(date))return json({sucesso:false,mensagem:"Informe um peso entre 0,1 e 300 kg e uma data válida."},400);const pet=await petPertenceAoTutor(env,tag,current.email);if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const result=await env.DB.batch([env.DB.prepare("INSERT INTO pet_pesos(tag_codigo,peso_kg,data_medicao,observacoes) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?))").bind(tag,Math.round(weight*100)/100,date,notes||null,tag,current.email),env.DB.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,'peso',?,?,?,1,?)`).bind(tag,`Peso registrado: ${String(Math.round(weight*100)/100).replace(".",",")} kg`,notes||null,`${date}T12:00:00.000Z`,current.email)]);if(Number(result[0]?.meta?.changes||0)!==1)return json({sucesso:false,mensagem:"Não foi possível registrar o peso."},409);return json({sucesso:true,mensagem:`Peso de ${pet.nome||"seu pet"} registrado.`,id:result[0]?.meta?.last_row_id||null},201)}catch(error){console.error("Erro ao salvar peso:",error);return json({sucesso:false,mensagem:"Não foi possível registrar o peso."},500)}}
export async function onRequestDelete({request,env}){try{const current=await obterSessaoTutor(request,env);if(!current)return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401);await ensure(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10),tag=clean(body.tagCodigo,100);if(!id||!tag)return json({sucesso:false,mensagem:"Registro inválido."},400);if(!await petPertenceAoTutor(env,tag,current.email))return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);const result=await env.DB.prepare("DELETE FROM pet_pesos WHERE id=? AND UPPER(tag_codigo)=UPPER(?) AND EXISTS(SELECT 1 FROM pets WHERE UPPER(pets.tag_codigo)=UPPER(pet_pesos.tag_codigo) AND LOWER(pets.email)=LOWER(?))").bind(id,tag,current.email).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Registro não encontrado."},404);return json({sucesso:true,mensagem:"Medição excluída."})}catch(error){console.error("Erro ao excluir peso:",error);return json({sucesso:false,mensagem:"Não foi possível excluir a medição."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
