import { enviarAlerta } from "../_shared/notificacoes.js";
import { obterSessaoTutor } from "../_lib/auth.js";

const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=UTF-8','Cache-Control':'no-store'}});
export async function onRequestGet(context){try{const db=context.env.DB,url=new URL(context.request.url),codigo=url.searchParams.get('tag')?.trim().toUpperCase();if(!codigo)return json({sucesso:false,status:'codigo-ausente',mensagem:'Código da tag não informado.'},400);
if(codigo==='DEMO')return json({sucesso:true,status:'ativa',demonstracao:true,perdido:false,pet:{nome:'Bento',especie:'Cachorro',raca:'Shih-tzu',sexo:'Macho',idade:'3 anos',comportamento:'Sou dócil e amigável. Aproxime-se com calma e fale comigo pelo nome.',nome_tutor:'Perfil demonstrativo',bairro:'Centro',cidade:'São Paulo',estado:'SP',foto_url:'/assets/menor.png',perdido:0}});
const tag=await db.prepare(`SELECT codigo,ativada,bloqueada FROM tags WHERE codigo=? LIMIT 1`).bind(codigo).first();if(!tag)return json({sucesso:false,status:'nao-existe',mensagem:'Esta tag não existe.'},404);if(Number(tag.bloqueada)===1)return json({sucesso:false,status:'bloqueada',mensagem:'Esta tag está bloqueada.'},403);if(Number(tag.ativada)!==1)return json({sucesso:true,status:'nao-ativada',codigo});
const pet=await db.prepare(`SELECT tag_codigo,nome,especie,raca,sexo,idade,comportamento,nome_tutor,whatsapp,email,bairro,cidade,estado,foto_url,perdido,status FROM pets WHERE tag_codigo=? ORDER BY id DESC LIMIT 1`).bind(codigo).first();if(!pet)return json({sucesso:false,status:'sem-pet',mensagem:'Pet não encontrado.'},404);
const novaLeitura=await registrarLeitura(db,context.request,codigo,context.request.cf);const sessao=await obterSessaoTutor(context.request,context.env,{atualizarUltimoAcesso:false});const proprioTutor=!!sessao&&sessao.email===String(pet.email||'').trim().toLowerCase();if(novaLeitura&&!proprioTutor){const alerta=enviarAlerta({env:context.env,pet,tipo:'leitura',cidade:context.request.cf?.city||'',estado:context.request.cf?.region||''});if(context.waitUntil)context.waitUntil(alerta);else await alerta}
const perdido=Number(pet.perdido)===1;let fotos=[];if(perdido){const galeria=await db.prepare(`SELECT url FROM pet_fotos WHERE tag_codigo=? ORDER BY ordem,id LIMIT 4`).bind(codigo).all();fotos=[pet.foto_url,...(galeria.results||[]).map(f=>f.url)].filter((u,i,l)=>u&&l.indexOf(u)===i).slice(0,5)}
const publico={tag_codigo:pet.tag_codigo,nome:pet.nome,especie:pet.especie,raca:pet.raca,sexo:pet.sexo,idade:pet.idade,comportamento:pet.comportamento,nome_tutor:pet.nome_tutor,whatsapp:pet.whatsapp,bairro:pet.bairro,cidade:pet.cidade,estado:pet.estado,foto_url:pet.foto_url,perdido:perdido?1:0,fotos};return json({sucesso:true,status:perdido?'perdido':'ativa',perdido,pet:publico})}catch(erro){console.error('Erro ao consultar tag:',erro);return json({sucesso:false,status:'erro',mensagem:'Não foi possível consultar a tag.'},500)}}
async function registrarLeitura(db,request,codigo,cf){try{const ip=request.headers.get('CF-Connecting-IP')||request.headers.get('X-Forwarded-For')||'',userAgent=request.headers.get('User-Agent')||'',agora=new Date(),cincoMinutosAtras=new Date(agora.getTime()-5*60*1000).toISOString();const ultima=await db.prepare(`SELECT id FROM leituras WHERE tag_codigo=? AND ip=? AND data_hora>=? ORDER BY id DESC LIMIT 1`).bind(codigo,ip,cincoMinutosAtras).first();if(ultima)return false;await db.prepare(`INSERT INTO leituras(tag_codigo,data_hora,ip,user_agent,pais,estado,cidade) VALUES(?,?,?,?,?,?,?)`).bind(codigo,agora.toISOString(),ip,userAgent,cf?.country||'',cf?.region||'',cf?.city||'').run();return true}catch(erro){console.error('Erro ao registrar leitura:',erro);return false}}
