const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=254)=>String(value??"").trim().slice(0,max);
function cookies(request){const result={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();if(!key)continue;try{result[key]=decodeURIComponent(part.slice(at+1).trim())}catch{result[key]=part.slice(at+1).trim()}}return result}
function token(request){const jar=cookies(request);for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT id,email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),sqlNow()).first()}
const sqlNow=()=>new Date().toISOString().replace("T"," ").slice(0,19);
const validEmail=value=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const html=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return[...bytes].map(value=>value.toString(16).padStart(2,"0")).join("")}
async function ensureTable(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS transferencias_pet(id INTEGER PRIMARY KEY AUTOINCREMENT,token_hash TEXT NOT NULL UNIQUE,tag_codigo TEXT NOT NULL,email_origem TEXT NOT NULL,email_destino TEXT NOT NULL,nome_destino TEXT NOT NULL,whatsapp_destino TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pendente',criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expira_em TEXT NOT NULL,aceito_em TEXT,cancelado_em TEXT)`).run()}
async function notify(env,{email,pet,from,acceptToken}){if(!env.RESEND_API_KEY)throw new Error("O envio de e-mail não está configurado.");const sender=env.EMAIL_REMETENTE||"BIRX Pets <onboarding@resend.dev>",url=`https://pets.birx.com.br/aceitar-transferencia?token=${encodeURIComponent(acceptToken)}`,petSafe=html(pet),fromSafe=html(from),response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:sender,to:[email],subject:`Convite para cuidar de ${pet} | BIRX Pets`,html:`<div style="font-family:Arial,sans-serif;max-width:540px;margin:auto;padding:30px;color:#17213a"><img src="https://pets.birx.com.br/assets/login.png" alt="BIRX Pets" style="width:150px"><h1 style="color:#17388f">Aceite a transferência de ${petSafe}</h1><p>${fromSafe} convidou você para ser o novo tutor responsável pelo perfil e pela tag de ${petSafe}.</p><p><strong>O pet ainda não saiu da conta atual.</strong> A mudança só acontecerá quando você aceitar.</p><p><a href="${url}" style="display:inline-block;padding:13px 20px;border-radius:10px;background:#2463eb;color:white;text-decoration:none;font-weight:bold">Revisar e aceitar convite</a></p><p style="color:#64748b;font-size:14px">Este convite expira em 7 dias. Se você não esperava recebê-lo, apenas ignore este e-mail.</p></div>`})});if(!response.ok)throw new Error("Não foi possível enviar o convite por e-mail.")}
async function authenticate(request,env){const current=await session(request,env);return current||json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401)}
export async function onRequestGet({request,env}){try{const current=await authenticate(request,env);if(current instanceof Response)return current;await ensureTable(env);const rows=await env.DB.prepare(`SELECT t.id,t.tag_codigo AS tagCodigo,t.email_destino AS emailDestino,t.nome_destino AS nomeDestino,t.criado_em AS criadoEm,t.expira_em AS expiraEm,p.nome AS petNome FROM transferencias_pet t INNER JOIN pets p ON UPPER(p.tag_codigo)=UPPER(t.tag_codigo) WHERE LOWER(t.email_origem)=LOWER(?) AND t.status='pendente' AND t.expira_em>CURRENT_TIMESTAMP ORDER BY t.id DESC`).bind(current.email).all();return json({sucesso:true,convites:rows.results||[]})}catch(error){console.error("Erro ao listar transferências:",error);return json({sucesso:false,mensagem:"Não foi possível consultar as transferências."},500)}}
export async function onRequestPost({request,env}){try{const current=await authenticate(request,env);if(current instanceof Response)return current;await ensureTable(env);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100).toUpperCase(),email=clean(body.novoEmail).toLowerCase(),name=clean(body.novoTutor,120),phone=clean(body.novoWhatsapp,30),confirmation=clean(body.confirmacao,120);if(!tag||!validEmail(email)||!name||!phone)return json({sucesso:false,mensagem:"Informe o novo tutor, e-mail e WhatsApp."},400);const pet=await env.DB.prepare("SELECT id,nome,nome_tutor,email FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,current.email).first();if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);if(email===String(current.email).toLowerCase())return json({sucesso:false,mensagem:"Informe um e-mail diferente da conta atual."},400);if(confirmation.toLocaleLowerCase("pt-BR")!==String(pet.nome).trim().toLocaleLowerCase("pt-BR"))return json({sucesso:false,mensagem:`Digite ${pet.nome} para confirmar a transferência.`},400);const pending=await env.DB.prepare("SELECT id FROM transferencias_pet WHERE UPPER(tag_codigo)=UPPER(?) AND status='pendente' AND expira_em>CURRENT_TIMESTAMP LIMIT 1").bind(tag).first();if(pending)return json({sucesso:false,mensagem:"Já existe um convite de transferência pendente para este pet."},409);const acceptToken=randomToken(),tokenHash=await sha(acceptToken),expires=new Date(Date.now()+7*86400000).toISOString().replace("T"," ").slice(0,19);await env.DB.prepare(`INSERT INTO transferencias_pet(token_hash,tag_codigo,email_origem,email_destino,nome_destino,whatsapp_destino,status,expira_em) VALUES(?,?,?,?,?,?,'pendente',?)`).bind(tokenHash,tag,current.email,email,name,phone,expires).run();try{await notify(env,{email,pet:pet.nome,from:pet.nome_tutor||"O tutor atual",acceptToken})}catch(error){await env.DB.prepare("DELETE FROM transferencias_pet WHERE token_hash=? AND status='pendente'").bind(tokenHash).run();throw error}return json({sucesso:true,mensagem:`Convite enviado para ${email}. ${pet.nome} continuará na sua conta até o aceite.`})}catch(error){console.error("Erro ao convidar transferência:",error);return json({sucesso:false,mensagem:error.message||"Não foi possível iniciar a transferência."},500)}}
export async function onRequestDelete({request,env}){try{const current=await authenticate(request,env);if(current instanceof Response)return current;await ensureTable(env);const body=await request.json().catch(()=>({})),id=Number.parseInt(body.id,10);if(!id)return json({sucesso:false,mensagem:"Convite inválido."},400);const result=await env.DB.prepare("UPDATE transferencias_pet SET status='cancelada',cancelado_em=CURRENT_TIMESTAMP WHERE id=? AND LOWER(email_origem)=LOWER(?) AND status='pendente'").bind(id,current.email).run();if(!result.meta?.changes)return json({sucesso:false,mensagem:"Convite não encontrado ou já finalizado."},404);return json({sucesso:true,mensagem:"Convite de transferência cancelado."})}catch(error){console.error("Erro ao cancelar transferência:",error);return json({sucesso:false,mensagem:"Não foi possível cancelar o convite."},500)}}
export async function onRequest(context){if(context.request.method==="GET")return onRequestGet(context);if(context.request.method==="POST")return onRequestPost(context);if(context.request.method==="DELETE")return onRequestDelete(context);return json({sucesso:false,mensagem:"Método não permitido."},405)}
