const H={"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const clean=(value,max=254)=>String(value??"").trim().slice(0,max);
function cookies(request){const result={};for(const part of(request.headers.get("Cookie")||"").split(";")){const at=part.indexOf("=");if(at<0)continue;const key=part.slice(0,at).trim();if(!key)continue;try{result[key]=decodeURIComponent(part.slice(at+1).trim())}catch{result[key]=part.slice(at+1).trim()}}return result}
function token(request){const jar=cookies(request);for(const key of["sessao_tutor","tutor_session","orbitek_session","orbitek_sessao","session"])if(jar[key])return jar[key];return""}
async function sha(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function session(request,env){const value=token(request);if(!value)return null;return env.DB.prepare("SELECT id,email FROM sessoes_tutor WHERE token_hash=? AND expira_em>? LIMIT 1").bind(await sha(value),new Date().toISOString().replace("T"," ").slice(0,19)).first()}
function validEmail(value){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
async function notify(env,{email,pet,from}){if(!env.RESEND_API_KEY)return;const sender=env.EMAIL_REMETENTE||"Orbitek Pets <onboarding@resend.dev>";try{await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:sender,to:[email],subject:`${pet} foi transferido para você | Orbitek Pets`,html:`<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;padding:30px"><img src="https://orbitekoficial.com.br/assets/login.png" alt="Orbitek Pets" style="width:150px"><h1 style="color:#17388f">${pet} agora está na sua conta</h1><p>O tutor ${from} transferiu o perfil e a tag de ${pet} para este e-mail.</p><p><a href="https://orbitekoficial.com.br/login" style="display:inline-block;padding:12px 18px;border-radius:10px;background:#2463eb;color:white;text-decoration:none;font-weight:bold">Acessar Orbitek Pets</a></p><p>Entre usando este e-mail para receber seu código de acesso.</p></div>`})})}catch(error){console.error("Aviso de transferência:",error)}}
export async function onRequestPost({request,env}){try{const current=await session(request,env);if(!current)return json({sucesso:false,autenticado:false,mensagem:"Sua sessão expirou."},401);const body=await request.json().catch(()=>({})),tag=clean(body.tagCodigo,100).toUpperCase(),email=clean(body.novoEmail).toLowerCase(),name=clean(body.novoTutor,120),phone=clean(body.novoWhatsapp,30),confirmation=clean(body.confirmacao,120);if(!tag||!validEmail(email)||!name||!phone)return json({sucesso:false,mensagem:"Informe o novo tutor, e-mail e WhatsApp."},400);const pet=await env.DB.prepare("SELECT id,nome,nome_tutor,email FROM pets WHERE UPPER(tag_codigo)=UPPER(?) AND LOWER(email)=LOWER(?) LIMIT 1").bind(tag,current.email).first();if(!pet)return json({sucesso:false,mensagem:"Pet não encontrado ou sem permissão."},403);if(email===String(current.email).toLowerCase())return json({sucesso:false,mensagem:"Informe um e-mail diferente da conta atual."},400);if(confirmation.toLocaleLowerCase("pt-BR")!==String(pet.nome).trim().toLocaleLowerCase("pt-BR"))return json({sucesso:false,mensagem:`Digite ${pet.nome} para confirmar a transferência.`},400);await env.DB.batch([env.DB.prepare("UPDATE pets SET email=?,nome_tutor=?,whatsapp=? WHERE id=? AND LOWER(email)=LOWER(?)").bind(email,name,phone,pet.id,current.email),env.DB.prepare(`INSERT INTO pet_timeline(tag_codigo,tipo,titulo,descricao,data_evento,automatico,criado_por) VALUES(?,'outro','Tutoria transferida',?,CURRENT_TIMESTAMP,1,?)`).bind(tag,`Transferido para ${name}.`,current.email)]);await notify(env,{email,pet:pet.nome,from:pet.nome_tutor||"anterior"});return json({sucesso:true,mensagem:`${pet.nome} foi transferido para ${name}. O novo tutor já pode entrar com ${email}.`})}catch(error){console.error("Erro ao transferir pet:",error);return json({sucesso:false,mensagem:"Não foi possível transferir o pet."},500)}}
export async function onRequest(context){if(context.request.method!=="POST")return json({sucesso:false,mensagem:"Método não permitido."},405);return onRequestPost(context)}
