function json(dados,status=200){return new Response(JSON.stringify(dados),{status,headers:{'Content-Type':'application/json; charset=UTF-8','Cache-Control':'no-store'}})}
function tagValida(codigo){return /^BIRX-\d{2}-\d{6}$/.test(codigo)||/^TAG-ORB-\d{2}-\d{6}$/.test(codigo)}
export async function onRequestPost(context){try{const{CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,DB}=context.env;if(!CLOUDINARY_CLOUD_NAME||!CLOUDINARY_API_KEY||!CLOUDINARY_API_SECRET)return json({sucesso:false,mensagem:'O envio de foto está temporariamente indisponível.'},503);const formulario=await context.request.formData(),arquivo=formulario.get('foto'),codigoTag=String(formulario.get('codigoTag')||'').trim().toUpperCase();if(!arquivo||typeof arquivo.arrayBuffer!=='function')return json({sucesso:false,mensagem:'Nenhuma foto foi enviada.'},400);if(!tagValida(codigoTag))return json({sucesso:false,mensagem:'Código da tag inválido.'},400);
const tag=await DB.prepare(`SELECT codigo,ativada,bloqueada FROM tags WHERE UPPER(codigo)=UPPER(?) LIMIT 1`).bind(codigoTag).first();if(!tag)return json({sucesso:false,mensagem:'Tag não encontrada.'},404);if(Number(tag.bloqueada)===1)return json({sucesso:false,mensagem:'Esta tag está bloqueada.'},403);if(Number(tag.ativada)===1)return json({sucesso:false,mensagem:'Esta tag já foi ativada.'},409);
const tipos=['image/jpeg','image/png','image/webp'];if(!tipos.includes(arquivo.type))return json({sucesso:false,mensagem:'Envie uma imagem JPG, PNG ou WEBP.'},400);if(arquivo.size>5*1024*1024)return json({sucesso:false,mensagem:'A foto deve ter no máximo 5 MB.'},400);
const timestamp=Math.floor(Date.now()/1000),publicId=limparCodigo(tag.codigo||codigoTag),pasta='orbitek-pets',stringAssinatura=`folder=${pasta}&overwrite=true&public_id=${publicId}&timestamp=${timestamp}${CLOUDINARY_API_SECRET}`,assinatura=await gerarSha1(stringAssinatura),dadosCloudinary=new FormData();dadosCloudinary.append('file',arquivo);dadosCloudinary.append('api_key',CLOUDINARY_API_KEY);dadosCloudinary.append('timestamp',String(timestamp));dadosCloudinary.append('signature',assinatura);dadosCloudinary.append('folder',pasta);dadosCloudinary.append('public_id',publicId);dadosCloudinary.append('overwrite','true');const resposta=await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`,{method:'POST',body:dadosCloudinary}),cloud=await resposta.json().catch(()=>({}));if(!resposta.ok||!cloud.secure_url){console.error('Erro Cloudinary:',cloud);return json({sucesso:false,mensagem:'Não foi possível enviar a foto.'},502)}return json({sucesso:true,fotoUrl:cloud.secure_url},201)}catch(erro){console.error('Erro no upload:',erro);return json({sucesso:false,mensagem:'Não foi possível enviar a foto.'},500)}}
export function onRequestGet(){return json({sucesso:false,mensagem:'Método não permitido.'},405)}
function limparCodigo(valor){return valor.toLowerCase().replace(/[^a-z0-9-_]/g,'-')}
async function gerarSha1(valor){const dados=new TextEncoder().encode(valor),hash=await crypto.subtle.digest('SHA-1',dados);return Array.from(new Uint8Array(hash)).map(byte=>byte.toString(16).padStart(2,'0')).join('')}
