import webpush from "web-push";
const times=(value)=>[...new Set((String(value||"").match(/(?:[01]\d|2[0-3]):[0-5]\d/g)||[]))];
function saoPaulo(date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date).reduce((all,part)=>(all[part.type]=part.value,all),{});return{date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`}}
async function sendReminders(env,now=new Date()){
  webpush.setVapidDetails(env.VAPID_SUBJECT||"mailto:contato@pets.birx.com.br",env.VAPID_PUBLIC_KEY,env.VAPID_PRIVATE_KEY);const local=saoPaulo(now),rows=await env.DB.prepare(`SELECT m.id AS medicamento_id,m.tag_codigo,m.nome,m.dosagem,m.horarios,p.nome AS pet_nome,p.email,a.id AS assinatura_id,a.endpoint,a.p256dh,a.auth FROM pet_medicamentos m INNER JOIN pets p ON UPPER(p.tag_codigo)=UPPER(m.tag_codigo) INNER JOIN push_assinaturas a ON LOWER(a.email)=LOWER(p.email) AND a.ativo=1 WHERE m.ativo=1 AND date(m.data_inicio)<=date(?) AND (m.data_fim IS NULL OR m.data_fim='' OR date(m.data_fim)>=date(?))`).bind(local.date,local.date).all();let sent=0;
  for(const item of rows.results||[])if(times(item.horarios).includes(local.time)){const window=`${local.date}T${local.time}`,reserved=await env.DB.prepare(`INSERT OR IGNORE INTO push_medicamentos_enviados(assinatura_id,medicamento_id,janela) VALUES(?,?,?)`).bind(item.assinatura_id,item.medicamento_id,window).run();if(!reserved.meta?.changes)continue;try{await webpush.sendNotification({endpoint:item.endpoint,keys:{p256dh:item.p256dh,auth:item.auth}},JSON.stringify({title:`Medicamento de ${item.pet_nome}`,body:`Hora de dar ${item.nome}${item.dosagem?` — ${item.dosagem}`:""}.`,tag:`med-${item.medicamento_id}-${window}`,url:"/tutor"}),{TTL:300});sent++}catch(error){console.error("Falha ao enviar push",error.statusCode,error.body);if(error.statusCode===404||error.statusCode===410)await env.DB.prepare("UPDATE push_assinaturas SET ativo=0 WHERE id=?").bind(item.assinatura_id).run()}}
  return sent;
}
export default{async scheduled(controller,env,ctx){ctx.waitUntil(sendReminders(env,new Date(controller.scheduledTime)))},async fetch(request,env){const url=new URL(request.url);if(url.pathname!=="/health")return new Response("Not found",{status:404});return Response.json({ok:true,worker:"birx-medication-reminders"})}};
export{sendReminders};
